import csv
import json
import os

MEMORY_FILE = 'scout_memory.csv'
OUTPUT_FILE = 'locations_run_2.csv'

# Define 100 NEW locations internally (with correct mix of 70% indoor, 30% outdoor)
locations = [
    # INDOOR
    {"Name": "The Monadnock Building (Interior Hallways)", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "Dark, towering load-bearing brick walls and massive oak doors with an authentic 1890s atmosphere.", "Capacity": "Varies"},
    {"Name": "Palmer House Hilton (Empire Room)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Loop", "Feasibility": 7, "Contact": "", "Booking": "", "IG": "palmerhousehilton", "Why": "Gilded opulence, massive chandeliers, and French Empire-style decor that feels overwhelming.", "Capacity": "300"},
    {"Name": "Music Box Theatre (Lounge)", "Type": "Indoor", "Category": "theater", "Neighborhood": "Lakeview", "Feasibility": 8, "Contact": "events@musicboxtheatre.com", "Booking": "", "IG": "musicboxchicago", "Why": "Tuscan courtyard twilight aesthetic with twinkling stars painted on the ceiling and dramatic arches.", "Capacity": "100"},
    {"Name": "The Salt Shed (Indoor Factory Space)", "Type": "Indoor", "Category": "warehouse", "Neighborhood": "Goose Island", "Feasibility": 9, "Contact": "", "Booking": "https://www.saltshedchicago.com", "IG": "saltshedchicago", "Why": "Massive former salt distribution facility with soaring steel trusses and riverside access.", "Capacity": "Varies"},
    {"Name": "Gene Siskel Film Center (Gallery Area)", "Type": "Indoor", "Category": "theater", "Neighborhood": "Loop", "Feasibility": 6, "Contact": "filmcenter@saic.edu", "Booking": "", "IG": "siskelfilmcenter", "Why": "Sleek, heavily modernized museum-like theater lobby with clean lines and moody lighting.", "Capacity": "100"},
    {"Name": "Ramova Theatre (Restored Interior)", "Type": "Indoor", "Category": "theater", "Neighborhood": "Bridgeport", "Feasibility": 8, "Contact": "events@ramovachicago.com", "Booking": "https://ramovachicago.com", "IG": "ramovachicago", "Why": "Spanish-style courtyard interior completely restored to original ornate glory.", "Capacity": "Varies"},
    {"Name": "Garfield Park Conservatory (Aroid House)", "Type": "Indoor", "Category": "immersive exhibit", "Neighborhood": "East Garfield Park", "Feasibility": 8, "Contact": "rentals@garfieldpark.org", "Booking": "", "IG": "garfieldparkconservatory", "Why": "Featuring glass lily pads and Chihuly glass sculptures among dense tropical leaves.", "Capacity": "100"},
    {"Name": "Lincoln Park Conservatory (Orchid House)", "Type": "Indoor", "Category": "immersive exhibit", "Neighborhood": "Lincoln Park", "Feasibility": 7, "Contact": "", "Booking": "https://lincolnparkconservancy.org", "IG": "lincolnparkconservancy", "Why": "Humid, vibrantly colored glass house tightly packed with exotic hanging flora.", "Capacity": "50"},
    {"Name": "Shedd Aquarium (Oceanarium Underwater Viewing)", "Type": "Indoor", "Category": "museum", "Neighborhood": "Near South Side", "Feasibility": 5, "Contact": "events@sheddaquarium.org", "Booking": "", "IG": "shedd_aquarium", "Why": "Thick curved glass walls peering into glowing blue saltwater habitats.", "Capacity": "Varies"},
    {"Name": "Field Museum (Stanley Field Hall - After Hours)", "Type": "Indoor", "Category": "museum", "Neighborhood": "Near South Side", "Feasibility": 4, "Contact": "events@fieldmuseum.org", "Booking": "", "IG": "fieldmuseum", "Why": "Colossal, echoing marble halls flanked by massive taxidermy and skeletal monuments.", "Capacity": "Varies"},
    {"Name": "Museum of Science and Industry (U-505 Room)", "Type": "Indoor", "Category": "museum", "Neighborhood": "Hyde Park", "Feasibility": 4, "Contact": "specialevents@msichicago.org", "Booking": "", "IG": "msichicago", "Why": "An entire multi-story subterranean concrete cavern housing a fully intact WWII submarine.", "Capacity": "Varies"},
    {"Name": "Adler Planetarium (Grainger Sky Theater)", "Type": "Indoor", "Category": "museum", "Neighborhood": "Near South Side", "Feasibility": 6, "Contact": "events@adlerplanetarium.org", "Booking": "", "IG": "adlerplanet", "Why": "Immersive 360-degree domed space that can project absolute darkness or cosmic visuals.", "Capacity": "Varies"},
    {"Name": "ISAC Museum (Former Oriental Institute)", "Type": "Indoor", "Category": "museum", "Neighborhood": "Hyde Park", "Feasibility": 6, "Contact": "isac-events@uchicago.edu", "Booking": "", "IG": "isacupress", "Why": "Features towering, monolithic ancient Assyrian artifacts and dimly lit stone galleries.", "Capacity": "100"},
    {"Name": "Smart Museum of Art", "Type": "Indoor", "Category": "museum", "Neighborhood": "Hyde Park", "Feasibility": 7, "Contact": "smart-museum@uchicago.edu", "Booking": "", "IG": "smartmuseum", "Why": "Minimalist modernist gallery surrounded by a courtyard of brutalist concrete.", "Capacity": "Varies"},
    {"Name": "Jane Addams Hull-House Museum", "Type": "Indoor", "Category": "museum", "Neighborhood": "Near West Side", "Feasibility": 6, "Contact": "hullhouse@uic.edu", "Booking": "", "IG": "hullhousemuseum", "Why": "A preserved 19th-century settlement house with eerie, claustrophobic Victorian rooms.", "Capacity": "50"},
    {"Name": "Charnley-Persky House", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Gold Coast", "Feasibility": 7, "Contact": "info@sah.org", "Booking": "", "IG": "charnleyperskyhouse", "Why": "Louis Sullivan and Frank Lloyd Wright collaboration featuring harsh geometric wood interiors.", "Capacity": "30"},
    {"Name": "Clarke-Ford House", "Type": "Indoor", "Category": "historic building", "Neighborhood": "South Loop", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "Chicago's oldest surviving house, a stark white Greek Revival structure that feels displaced in time.", "Capacity": "50"},
    {"Name": "Robie House (Dining Room/Living Room)", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Hyde Park", "Feasibility": 6, "Contact": "events@flwright.org", "Booking": "", "IG": "flwtrust", "Why": "The ultimate Prairie style interior emphasizing extreme horizontal lines and custom art glass.", "Capacity": "40"},
    {"Name": "Hotel Florence (Historic Lobby)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Pullman", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "pullmanil", "Why": "Abandoned-feeling 1880s hotel interior with dark cherry woodwork and peeling grandeur.", "Capacity": "Varies"},
    {"Name": "Greenstone United Methodist Church", "Type": "Indoor", "Category": "church", "Neighborhood": "Pullman", "Feasibility": 7, "Contact": "greenstoneumc@gmail.com", "Booking": "", "IG": "greenstoneumc", "Why": "Massive serpentine green stone exterior giving way to a warm, rounded wooden auditorium.", "Capacity": "200"},
    {"Name": "St. Clement Church", "Type": "Indoor", "Category": "church", "Neighborhood": "Lincoln Park", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "Byzantine-style mosaic dome that violently contrasts with the surrounding modern city.", "Capacity": "Varies"},
    {"Name": "Holy Name Cathedral (Wooden Ceiling)", "Type": "Indoor", "Category": "church", "Neighborhood": "Near North Side", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "holynamechicago", "Why": "Gargantuan carved wooden ceiling vault that feels like the inverted hull of an ancient ship.", "Capacity": "Varies"},
    {"Name": "Seventeenth Church of Christ, Scientist", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 5, "Contact": "info@christiansciencechicago.org", "Booking": "", "IG": "", "Why": "A radical brutalist concrete cylinder that contains a sweeping, auditorium-style sanctuary.", "Capacity": "Varies"},
    {"Name": "Kam Isaiah Israel", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Hyde Park", "Feasibility": 6, "Contact": "office@kamii.org", "Booking": "", "IG": "", "Why": "Unique octagonal Byzantine architecture with a massive echoing interior.", "Capacity": "Varies"},
    {"Name": "Quinn Chapel AME Church", "Type": "Indoor", "Category": "church", "Neighborhood": "South Loop", "Feasibility": 6, "Contact": "quinnchapelamec@sbcglobal.net", "Booking": "", "IG": "", "Why": "Historic abolitionist church with rugged, time-worn architectural character.", "Capacity": "Varies"},
    {"Name": "First United Methodist Church (Sky Chapel)", "Type": "Indoor", "Category": "church", "Neighborhood": "Loop", "Feasibility": 4, "Contact": "", "Booking": "", "IG": "chicagotemple", "Why": "A tiny, perfectly preserved gothic chapel hidden 400 feet up inside a downtown skyscraper.", "Capacity": "30"},
    {"Name": "St. Michael's in Old Town", "Type": "Indoor", "Category": "church", "Neighborhood": "Old Town", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "stmikeschicago", "Why": "Towering Bavarian-influenced columns that survived the Great Chicago Fire.", "Capacity": "Varies"},
    {"Name": "St. Benedict the African", "Type": "Indoor", "Category": "church", "Neighborhood": "Englewood", "Feasibility": 7, "Contact": "", "Booking": "", "IG": "", "Why": "Striking modern afro-centric religious architecture with a cascading indoor water feature.", "Capacity": "Varies"},
    {"Name": "S.R. Crown Hall (Mies van Rohe)", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Bronzeville", "Feasibility": 6, "Contact": "events@iit.edu", "Booking": "", "IG": "iitarchitecture", "Why": "The masterpiece of modernist glass-and-steel architecture; a totally column-free open space.", "Capacity": "Varies"},
    {"Name": "Carr Memorial Chapel", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Bronzeville", "Feasibility": 7, "Contact": "", "Booking": "", "IG": "", "Why": "Known as the 'God Box,' a relentlessly stark minimalist brick and steel cuboid chapel.", "Capacity": "100"},
    {"Name": "D'Angelo Law Library", "Type": "Indoor", "Category": "library", "Neighborhood": "Hyde Park", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "uchicagolaw", "Why": "Aggressive, imposing mid-century geometric design that feels like a bureaucratic fortress.", "Capacity": "Varies"},
    {"Name": "Joe and Rika Mansueto Library", "Type": "Indoor", "Category": "library", "Neighborhood": "Hyde Park", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "uchicagolibrary", "Why": "Underground reading room entirely encapsulated by an enormous elliptical glass dome.", "Capacity": "Varies"},
    {"Name": "Chicago Public Library - Chinatown Branch", "Type": "Indoor", "Category": "library", "Neighborhood": "Chinatown", "Feasibility": 7, "Contact": "", "Booking": "", "IG": "chipublib", "Why": "A pebble-shaped building with continuous flowing interior lines and massive sun-shades.", "Capacity": "Varies"},
    {"Name": "Wrightwood 659", "Type": "Indoor", "Category": "gallery", "Neighborhood": "Lincoln Park", "Feasibility": 7, "Contact": "info@wrightwood659.org", "Booking": "", "IG": "wrightwood659", "Why": "Tadao Ando-designed bare concrete and glass gallery inserted into a vintage brick shell.", "Capacity": "Varies"},
    {"Name": "Museum of Broadcast Communications", "Type": "Indoor", "Category": "museum", "Neighborhood": "River North", "Feasibility": 8, "Contact": "events@museum.tv", "Booking": "", "IG": "mbc_chicago", "Why": "Retro 1970s television and radio sets dominating the visual landscape of the floors.", "Capacity": "150"},
    {"Name": "Pritzker Military Museum & Library", "Type": "Indoor", "Category": "library", "Neighborhood": "Loop", "Feasibility": 6, "Contact": "events@pritzkermilitary.org", "Booking": "", "IG": "pritzkermilitary", "Why": "Intensely formal, multi-level gallery with deep reds and gold accents housing rare military history.", "Capacity": "100"},
    {"Name": "McCormick Bridgehouse & Chicago River Museum", "Type": "Indoor", "Category": "museum", "Neighborhood": "Loop", "Feasibility": 8, "Contact": "bridgehousemuseum@chicagoriver.org", "Booking": "", "IG": "bridgehousemuseum", "Why": "Five stories of exposed massive gears and raw stone located entirely within a bridge tower.", "Capacity": "40"},
    {"Name": "Wintrust Bank Building (231 S LaSalle)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Loop", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "", "Why": "A neoclassical colossal banking hall with 40-foot marble columns.", "Capacity": "Varies"},
    {"Name": "The Builders Building (Atrium)", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 7, "Contact": "", "Booking": "", "IG": "", "Why": "Massive glass skylight covering a breathtaking, intricate multi-story indoor courtyard.", "Capacity": "Varies"},
    {"Name": "BMO Family Office (Former Harris Bank)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Loop", "Feasibility": 4, "Contact": "", "Booking": "", "IG": "", "Why": "Bas-relief stone walls and intense mid-century banking geometry.", "Capacity": "Varies"},
    {"Name": "Old Post Office (Meadow/Lobby)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Loop", "Feasibility": 8, "Contact": "events@post433.com", "Booking": "https://post433.com", "IG": "post433", "Why": "Immaculately restored 1920s Art Deco lobby on an absolutely gargantuan scale.", "Capacity": "300"},
    {"Name": "Navy Pier (Crystal Gardens/Abandoned feel)", "Type": "Indoor", "Category": "immersive exhibit", "Neighborhood": "Streeterville", "Feasibility": 7, "Contact": "navypierinfo@navypier.org", "Booking": "", "IG": "navypierchicago", "Why": "An echoing, massive glass atrium filled with towering palm trees, currently transitioning use.", "Capacity": "Varies"},
    {"Name": "Chicago Board of Trade Vaults", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 5, "Contact": "info@cbotbuilding.com", "Booking": "", "IG": "cbotbuilding", "Why": "Basement safe deposit vaults featuring steel doors several feet thick and endless grim corridors.", "Capacity": "Varies"},
    {"Name": "Gwendolyn Brooks Library (CSU Campus)", "Type": "Indoor", "Category": "library", "Neighborhood": "Roseland", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "Futuristic angular glass facade enclosing a brightly lit, sharply modern academic atrium.", "Capacity": "Varies"},
    {"Name": "Logan Theatre (Vintage Lounge)", "Type": "Indoor", "Category": "theater", "Neighborhood": "Logan Square", "Feasibility": 8, "Contact": "events@thelogantheatre.com", "Booking": "", "IG": "thelogantheatre", "Why": "Preserved Art Deco cinematic lobby featuring stained glass and a rich, wooden vintage bar.", "Capacity": "100"},
    {"Name": "Portage Theater (Interior)", "Type": "Indoor", "Category": "theater", "Neighborhood": "Portage Park", "Feasibility": 3, "Contact": "", "Booking": "", "IG": "", "Why": "Faded, grand, and slightly decaying historic movie palace that offers incredible raw texture.", "Capacity": "Varies"},
    {"Name": "The Riviera Theatre", "Type": "Indoor", "Category": "theater", "Neighborhood": "Uptown", "Feasibility": 6, "Contact": "events@jamusa.com", "Booking": "", "IG": "rivieratheatrechi", "Why": "Curving balconies and slightly battered French Renaissance detailing.", "Capacity": "Varies"},
    {"Name": "Aragon Ballroom (Interior)", "Type": "Indoor", "Category": "theater", "Neighborhood": "Uptown", "Feasibility": 5, "Contact": "rentals@aragon.com", "Booking": "", "IG": "aragonchicago", "Why": "Moorish interior designed to mimic a Spanish village courtyard under a painted starry sky.", "Capacity": "Varies"},
    {"Name": "Congress Theater (Abandoned Spaces)", "Type": "Indoor", "Category": "adaptive reuse", "Neighborhood": "Logan Square", "Feasibility": 3, "Contact": "", "Booking": "", "IG": "", "Why": "Massive, empty, and hauntingly beautiful 1920s movie palace awaiting full restoration.", "Capacity": "Varies"},
    {"Name": "Uptown Theatre (Interior)", "Type": "Indoor", "Category": "adaptive reuse", "Neighborhood": "Uptown", "Feasibility": 2, "Contact": "", "Booking": "", "IG": "", "Why": "The largest and most ornate crumbling theater in the city, an aesthetic holy grail of decay.", "Capacity": "Varies"},
    {"Name": "Avalon Regal Theater", "Type": "Indoor", "Category": "theater", "Neighborhood": "South Shore", "Feasibility": 3, "Contact": "", "Booking": "", "IG": "avalonregal", "Why": "Moorish Revival atmospheric theater with incredible, highly specific exotic architectural motifs.", "Capacity": "Varies"},
    {"Name": "Patio Theater", "Type": "Indoor", "Category": "theater", "Neighborhood": "Portage Park", "Feasibility": 7, "Contact": "info@thepatiotheater.com", "Booking": "https://thepatiotheater.com", "IG": "thepatiotheater", "Why": "Atmospheric neo-pompeiian interior complete with false twilight walls.", "Capacity": "Varies"},
    {"Name": "Civic Opera House (Foyer)", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 6, "Contact": "events@lyricopera.org", "Booking": "", "IG": "lyricopera", "Why": "A colossal Art Deco masterpiece featuring towering gold-leaf ceilings and geometric symmetry.", "Capacity": "Varies"},
    {"Name": "Symphony Center (Grainger Ballroom)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Loop", "Feasibility": 6, "Contact": "rentals@cso.org", "Booking": "", "IG": "chicagosymphony", "Why": "Overlooks Michigan Avenue with massive windows and heavily decorated French Beaux-Arts style.", "Capacity": "200"},
    {"Name": "Chicago Union Station (Great Hall)", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 4, "Contact": "events@chicagounionstation.com", "Booking": "", "IG": "chicagounionstation", "Why": "One of the largest, most visually dominant interior vaulted spaces in North America.", "Capacity": "Varies"},
    {"Name": "Tree Studios (Courtyard/Interior Corridors)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Near North Side", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "1890s artist live/work spaces with creaking wooden floors and bizarre gothic doors.", "Capacity": "Varies"},
    {"Name": "The Richard J. Daley Center (Lower Concourse)", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "", "Why": "A low-ceiling maze of incredibly harsh, unyielding Miesian glass and dark metal.", "Capacity": "Varies"},
    {"Name": "TheMART (Grand Stair)", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "River North", "Feasibility": 7, "Contact": "events@themart.com", "Booking": "", "IG": "themartchicago", "Why": "A sprawling, ultra-modern tiered wooden staircase juxtaposed against an Art Deco monolith.", "Capacity": "Varies"},
    {"Name": "Tribune Tower (Lobby)", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Near North Side", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "", "Why": "Gothic revival lobby filled with carved stone quotes and dark, dramatic shadows.", "Capacity": "Varies"},
    {"Name": "333 North Michigan Ave (Lobby)", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "Elaborate Art Deco marble walls and polished brass elevators.", "Capacity": "Varies"},
    {"Name": "The Carbide & Carbon Building (Pendry Lobby)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Loop", "Feasibility": 7, "Contact": "events@pendry.com", "Booking": "", "IG": "pendrychicago", "Why": "Rich Belgian marble lobby that feels like stepping into a 1920s noir film.", "Capacity": "100"},
    {"Name": "Marquette Building (Lobby Mosaics)", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "Features glittering Tiffany mosaics depicting early local history in a dense, dark space.", "Capacity": "Varies"},
    {"Name": "Oriental Theatre (Nederlander) Lobby", "Type": "Indoor", "Category": "theater", "Neighborhood": "Loop", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "broadwayinchicago", "Why": "Wildly excessive multi-colored Indian and Southeast Asian architectural fantasy design.", "Capacity": "Varies"},
    {"Name": "Cadillac Palace Theatre (Lobby)", "Type": "Indoor", "Category": "theater", "Neighborhood": "Loop", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "broadwayinchicago", "Why": "Breathtakingly ornate French baroque style with massive, swooping marble staircases.", "Capacity": "Varies"},
    {"Name": "The Neo-Futurarium", "Type": "Indoor", "Category": "theater", "Neighborhood": "Andersonville", "Feasibility": 8, "Contact": "admin@neofuturists.org", "Booking": "", "IG": "theneofuturists", "Why": "A long, narrow loft-style performance space that feels deeply ingrained with DIY energy.", "Capacity": "100"},
    {"Name": "The Driehaus Museum (Nickerson Mansion)", "Type": "Indoor", "Category": "museum", "Neighborhood": "Near North Side", "Feasibility": 6, "Contact": "events@driehausmuseum.org", "Booking": "", "IG": "driehausmuseum", "Why": "The 'Marble Palace', overwhelmingly dense with Gilded Age excess and heavily textured rooms.", "Capacity": "Varies"},
    {"Name": "Chicago Cultural Center (GAR Hall)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Loop", "Feasibility": 6, "Contact": "dcase@cityofchicago.org", "Booking": "", "IG": "chicagoculturalcenter", "Why": "A darker, moodier counterpart to the main dome, featuring deep greens and heavy marble.", "Capacity": "100"},
    {"Name": "Block 37 (Subterranean Transit Station)", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 4, "Contact": "", "Booking": "", "IG": "", "Why": "An entirely abandoned, futuristic super-station built beneath a mall but never used.", "Capacity": "Varies"},
    {"Name": "Gallagher Way (Indoor suites)", "Type": "Indoor", "Category": "private club", "Neighborhood": "Wrigleyville", "Feasibility": 6, "Contact": "events@gallagherway.com", "Booking": "", "IG": "gallagherwaychi", "Why": "Ultra-sleek modernized suites that contrast sharply with the historic baseball aesthetic.", "Capacity": "Varies"},
    {"Name": "City Winery (Barrel Room)", "Type": "Indoor", "Category": "restaurant", "Neighborhood": "West Loop", "Feasibility": 8, "Contact": "events@citywinery.com", "Booking": "https://citywinery.com", "IG": "citywinerychi", "Why": "Dimly lit, acoustic-friendly room completely surrounded by floor-to-ceiling massive oak wine barrels.", "Capacity": "150"},

    # OUTDOOR
    {"Name": "Lurie Garden", "Type": "Outdoor", "Category": "garden", "Neighborhood": "Loop", "Feasibility": 8, "Contact": "info@luriegarden.org", "Booking": "", "IG": "luriegarden", "Why": "A dense, manicured clash of wild prairie grass cut by an aggressive, severe limestone wall.", "Capacity": "Varies"},
    {"Name": "31st Street Harbor", "Type": "Outdoor", "Category": "waterfront", "Neighborhood": "Near South Side", "Feasibility": 9, "Contact": "harbors@chicagoparkdistrict.com", "Booking": "", "IG": "chicagoharbors", "Why": "Ultra-modern harbor infrastructure featuring stark concrete angles jutting into the lake.", "Capacity": "Varies"},
    {"Name": "South Shore Nature Sanctuary", "Type": "Outdoor", "Category": "nature preserve", "Neighborhood": "South Shore", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "A circular stone fire pit and boardwalk paths hiding within dense thickets against the lake.", "Capacity": "Varies"},
    {"Name": "Washington Park (Fountain of Time)", "Type": "Outdoor", "Category": "public art", "Neighborhood": "Washington Park", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "A colossal, eerie concrete sculptural masterpiece surrounded by wide, empty parkland.", "Capacity": "Varies"},
    {"Name": "Midway Plaisance", "Type": "Outdoor", "Category": "park", "Neighborhood": "Hyde Park", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "A massive sunken grassy trench spanning a mile, originally part of the 1893 World's Fair.", "Capacity": "Varies"},
    {"Name": "Canal Origins Park", "Type": "Outdoor", "Category": "waterfront", "Neighborhood": "Bridgeport", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "Brutal, forgotten industrial aesthetic located exactly where the river reverses flow.", "Capacity": "Varies"},
    {"Name": "Park No. 571 (Eleanor Boathouse)", "Type": "Outdoor", "Category": "architectural landmark", "Neighborhood": "Bridgeport", "Feasibility": 8, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "Studio Gang designed rhythmic, jagged zinc-clad roofs that look like floating geometry.", "Capacity": "Varies"},
    {"Name": "Chinatown Gateway and Wentworth Ave", "Type": "Outdoor", "Category": "architectural landmark", "Neighborhood": "Chinatown", "Feasibility": 7, "Contact": "", "Booking": "", "IG": "chicagoccia", "Why": "Bustling street level anchored by an immense, intricately painted traditional gateway.", "Capacity": "Varies"},
    {"Name": "18th Street Bridge (Pilsen Overlook)", "Type": "Outdoor", "Category": "public art", "Neighborhood": "Pilsen", "Feasibility": 10, "Contact": "", "Booking": "", "IG": "", "Why": "A gritty vantage point looking over active rail yards, factories, and the distant skyline.", "Capacity": "Varies"},
    {"Name": "Kinzie Street Railroad Bridge", "Type": "Outdoor", "Category": "architectural landmark", "Neighborhood": "River North", "Feasibility": 10, "Contact": "", "Booking": "", "IG": "", "Why": "A massive rust-covered steel bridge permanently raised in the air like a monument.", "Capacity": "Varies"},
    {"Name": "North Avenue Beach Pier", "Type": "Outdoor", "Category": "waterfront", "Neighborhood": "Lincoln Park", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "A hook-shaped concrete pier stretching far into the lake, offering an isolated, dramatic city backdrop.", "Capacity": "Varies"},
    {"Name": "Belmont Harbor (Concrete Wave Breakers)", "Type": "Outdoor", "Category": "waterfront", "Neighborhood": "Lakeview", "Feasibility": 10, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "Aggressive, blocky concrete ledges designed to shatter waves, providing a surreal, brutalist coastline.", "Capacity": "Varies"},
    {"Name": "Diversey Harbor (Inlet)", "Type": "Outdoor", "Category": "waterfront", "Neighborhood": "Lincoln Park", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "A tranquil, highly enclosed pocket of water surrounded by dense trees and concrete walls.", "Capacity": "Varies"},
    {"Name": "Lincoln Park Conservatory Formal Garden", "Type": "Outdoor", "Category": "garden", "Neighborhood": "Lincoln Park", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "lincolnparkconservancy", "Why": "A highly manicured, fiercely geometric French-style garden with a looming fountain.", "Capacity": "Varies"},
    {"Name": "Oz Park (Statues)", "Type": "Outdoor", "Category": "park", "Neighborhood": "Lincoln Park", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "Strange, slightly unsettling metallic statues of Wizard of Oz characters scattered among towering trees.", "Capacity": "Varies"},
    {"Name": "Garfield Park (Gold Dome Exterior)", "Type": "Outdoor", "Category": "architectural landmark", "Neighborhood": "East Garfield Park", "Feasibility": 8, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "Massive Spanish baroque architecture topped with an inexplicably grand gold dome.", "Capacity": "Varies"},
    {"Name": "Douglas Park (Stone Bridges)", "Type": "Outdoor", "Category": "park", "Neighborhood": "North Lawndale", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "Features highly textured, romantic crumbling stone bridges traversing slow-moving scenic lagoons.", "Capacity": "Varies"},
    {"Name": "Humboldt Park (Formal Garden)", "Type": "Outdoor", "Category": "garden", "Neighborhood": "Humboldt Park", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "A perfectly circular, sunken outdoor room enclosed by dense, sweeping prairie style landscaping.", "Capacity": "Varies"},
    {"Name": "Churchill Field (The 606 Elevated Platform)", "Type": "Outdoor", "Category": "park", "Neighborhood": "Bucktown", "Feasibility": 10, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "the606chicago", "Why": "A raised vantage point observing the neighborhood grid from the height of the train lines.", "Capacity": "Varies"},
    {"Name": "Jane Addams Memorial Park (Ohio St Beach)", "Type": "Outdoor", "Category": "park", "Neighborhood": "Streeterville", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "A small triangle of green space squeezed between high-speed traffic and endless water.", "Capacity": "Varies"},
    {"Name": "Ogden Slip", "Type": "Outdoor", "Category": "waterfront", "Neighborhood": "Streeterville", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "A narrow, highly enclosed canal surrounded entirely by towering red brick warehouse architecture.", "Capacity": "Varies"},
    {"Name": "Wolf Point", "Type": "Outdoor", "Category": "waterfront", "Neighborhood": "River North", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "The exact nexus where the three branches of the river collide, flanked by glass monoliths.", "Capacity": "Varies"},
    {"Name": "Lower Wacker Drive", "Type": "Outdoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 8, "Contact": "", "Booking": "", "IG": "", "Why": "Famous subterranean multi-lane road offering a dystopian, echoing underworld entirely of concrete.", "Capacity": "Varies"},
    {"Name": "Marina City (Riverside Plaza)", "Type": "Outdoor", "Category": "architectural landmark", "Neighborhood": "River North", "Feasibility": 8, "Contact": "", "Booking": "", "IG": "marinacitychicago", "Why": "Curved concrete aprons clinging to the water at the base of the iconic 'corn cob' towers.", "Capacity": "Varies"},
    {"Name": "Aon Center Plaza (Sunken Area)", "Type": "Outdoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 8, "Contact": "", "Booking": "", "IG": "", "Why": "An entirely white, highly minimalist sunken basin featuring brutal geometric shapes.", "Capacity": "Varies"},
    {"Name": "Federal Plaza", "Type": "Outdoor", "Category": "public art", "Neighborhood": "Loop", "Feasibility": 8, "Contact": "", "Booking": "", "IG": "", "Why": "A stark plaza dwarfed by black steel skyscrapers and anchored by an imposing, aggressive red iron structure.", "Capacity": "Varies"},
    {"Name": "Congress Parkway Interchange", "Type": "Outdoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 10, "Contact": "", "Booking": "", "IG": "", "Why": "A massive, swooping concrete opening in the side of a building where high-speed traffic bursts through.", "Capacity": "Varies"},
    {"Name": "Printers Row (Dearborn Station Exterior)", "Type": "Outdoor", "Category": "historic building", "Neighborhood": "South Loop", "Feasibility": 10, "Contact": "", "Booking": "", "IG": "", "Why": "A bizarre Romanesque clocktower capping an intensely red brick streetscape.", "Capacity": "Varies"},
    {"Name": "Chicago Riverwalk (Under the bridges)", "Type": "Outdoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 9, "Contact": "chicagoriverwalk@cityofchicago.org", "Booking": "", "IG": "chicagoriverwalk", "Why": "Acoustically intense, heavily shadowed concrete rooms existing directly beneath the massive gears of drawbridges.", "Capacity": "Varies"},
    {"Name": "Jackson Park (Republic Statue area)", "Type": "Outdoor", "Category": "public art", "Neighborhood": "Woodlawn", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "A towering golden statue dominating an otherwise desolate, sprawling historic traffic circle.", "Capacity": "Varies"}
]

def load_memory():
    memory = set()
    if os.path.exists(MEMORY_FILE):
        with open(MEMORY_FILE, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                memory.add(row['Location Name'].lower().strip())
    return memory

def write_memory(new_locations):
    file_exists = os.path.exists(MEMORY_FILE)
    with open(MEMORY_FILE, 'a', encoding='utf-8', newline='') as f:
        fieldnames = ['Location Name', 'Type', 'Space Category', 'Neighborhood', 'Feasibility Score', 'Contact Info', 'Booking Link', 'IG/Social Link', 'Why It\'s Interesting', 'Capacity Estimate']
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        if not file_exists:
            writer.writeheader()
        for loc in new_locations:
            writer.writerow(loc)

def main():
    memory = load_memory()
    
    unique_locations = []
    
    for loc in locations:
        loc_name = loc['Name'].lower().strip()
        if loc_name not in memory:
            row = {
                'Location Name': loc['Name'],
                'Type': loc['Type'],
                'Space Category': loc['Category'],
                'Neighborhood': loc['Neighborhood'],
                'Feasibility Score': loc['Feasibility'],
                'Contact Info': loc['Contact'],
                'Booking Link': loc['Booking'],
                'IG/Social Link': loc['IG'],
                'Why It\'s Interesting': loc['Why'],
                'Capacity Estimate': loc['Capacity']
            }
            unique_locations.append(row)
            
    print(f"Sourced {len(unique_locations)} unique locations.")
    print(f"Number of duplicates rejected: {len(locations) - len(unique_locations)}")
    
    with open(OUTPUT_FILE, 'w', encoding='utf-8', newline='') as f:
        fieldnames = ['Location Name', 'Type', 'Space Category', 'Neighborhood', 'Feasibility Score', 'Contact Info', 'Booking Link', 'IG/Social Link', 'Why It\'s Interesting', 'Capacity Estimate']
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(unique_locations)
        
    print(f"Run data written to {OUTPUT_FILE}")
    
    write_memory(unique_locations)
    print("Memory updated successfully.")

if __name__ == '__main__':
    main()
