import csv
import json
import os

MEMORY_FILE = 'scout_memory.csv'
OUTPUT_FILE = 'locations_run_4.csv'


locations = [
    # INDOOR
    {"Name": "Peggy Notebaert Nature Museum (Judy Istock Butterfly Haven)", "Type": "Indoor", "Category": "immersive exhibit", "Neighborhood": "Lincoln Park", "Feasibility": 8, "Contact": "events@naturemuseum.org", "Booking": "naturemuseum.org", "IG": "naturemuseum", "Why": "A stunning, humid, 2,700-square-foot glass greenhouse filled with over 1,000 fluttering butterflies and exotic flowers.", "Capacity": "100"},
    {"Name": "Auditorium Theatre (Ganz Hall at Roosevelt University)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Loop", "Feasibility": 6, "Contact": "events@roosevelt.edu", "Booking": "roosevelt.edu", "IG": "rooseveltulibrary", "Why": "A highly intimate, wildly ornate Sullivan/Wright designed recital hall completely covered in intricate gold stenciling and wood.", "Capacity": "150"},
    {"Name": "University Club of Chicago (Cathedral Hall)", "Type": "Indoor", "Category": "private club", "Neighborhood": "Loop", "Feasibility": 3, "Contact": "", "Booking": "", "IG": "ucco1887", "Why": "Soaring, towering gothic stained glass windows mimicking a medieval cathedral housed entirely within a private club.", "Capacity": "200"},
    {"Name": "The Fortnightly of Chicago (Lathrop House)", "Type": "Indoor", "Category": "private club", "Neighborhood": "Gold Coast", "Feasibility": 4, "Contact": "info@fortnightlychicago.org", "Booking": "", "IG": "", "Why": "A perfectly manicured, deeply silent Georgian Revival mansion bursting with antique feminine elegance and floral wallpapers.", "Capacity": "80"},
    {"Name": "Firehouse Chicago", "Type": "Indoor", "Category": "adaptive reuse", "Neighborhood": "Edgewater", "Feasibility": 9, "Contact": "events@firehousechicago.com", "Booking": "firehousechicago.com", "IG": "firehousechicago", "Why": "A beautifully restored vintage firehouse featuring exposed white brick, antique tin ceilings, and massive arched bay doors.", "Capacity": "100"},
    {"Name": "St. Mary of the Angels (Main Sanctuary)", "Type": "Indoor", "Category": "church", "Neighborhood": "Bucktown", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "stmaryoftheangels", "Why": "Topped by a gigantic Renaissance-style dome that baths the intensely wide, sweeping nave in holy sunlight.", "Capacity": "Varies"},
    {"Name": "The Geraghty", "Type": "Indoor", "Category": "warehouse", "Neighborhood": "Pilsen", "Feasibility": 9, "Contact": "events@thegeraghty.com", "Booking": "thegeraghty.com", "IG": "thegeraghty", "Why": "A massive, hyper-modern, completely open warehouse explicitly designed to be a blank canvas for aggressive architectural lighting.", "Capacity": "500"},
    {"Name": "Wrigley Building (Breezeway & North Lobby)", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Near North Side", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "thewrigleybuilding", "Why": "Pristine, violently bright white terra cotta arcades leading into a deeply rich, highly polished brass and wood lobby.", "Capacity": "Varies"},
    {"Name": "Chicago History Museum (Diorama Hall)", "Type": "Indoor", "Category": "museum", "Neighborhood": "Lincoln Park", "Feasibility": 6, "Contact": "events@chicagohistory.org", "Booking": "", "IG": "chicagohistory", "Why": "A dark, highly retro, mood-lit corridor lined with deeply detailed, unsettling 1930s miniature historical dioramas.", "Capacity": "Varies"},
    {"Name": "The Money Museum (Historic Vault)", "Type": "Indoor", "Category": "museum", "Neighborhood": "Loop", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "", "Why": "Deeply subterranean Federal Reserve exhibit featuring a monolithic solid steel bank vault door protecting billions.", "Capacity": "30"},
    {"Name": "Ping Tom Memorial Park (Fieldhouse)", "Type": "Indoor", "Category": "cultural center", "Neighborhood": "Chinatown", "Feasibility": 8, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "Striking contemporary adaptation of traditional Chinese architecture surrounding a completely sleek glass indoor pool.", "Capacity": "100"},
    {"Name": "Chicago Cultural Center (Washington Street Lobby & Mosaic Stairs)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Loop", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "chicagoculturalcenter", "Why": "Sweeping, terrifyingly grand Carrara marble staircases completely encrusted in glittering neo-Byzantine mosaics.", "Capacity": "Varies"},
    {"Name": "The Palmer House Hilton (Grand Lobby Ceiling)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Loop", "Feasibility": 7, "Contact": "", "Booking": "", "IG": "palmerhousehilton", "Why": "Lounge under a dizzying, deeply opulent vaulted ceiling entirely covered in hand-painted Greek mythology frescoes.", "Capacity": "Varies"},
    {"Name": "The Drake Hotel (Gold Coast Room)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Gold Coast", "Feasibility": 7, "Contact": "", "Booking": "", "IG": "thedrakehotel", "Why": "An incredibly regal, colonnaded ballroom overlooking the lake that drips with 1920s high society exclusivity.", "Capacity": "Varies"},
    {"Name": "Chicago Athletic Association (Stagg Observatory/Drawing Room)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Loop", "Feasibility": 7, "Contact": "events@chicagoathletichotel.com", "Booking": "", "IG": "chicagoathletichotel", "Why": "A darkly lit, masculine parlor boasting heavy oak panelling and towering Gothic windows facing the park.", "Capacity": "100"},
    {"Name": "Freehand Chicago (Lobby Lounge)", "Type": "Indoor", "Category": "adaptive reuse", "Neighborhood": "River North", "Feasibility": 8, "Contact": "events@freehandhotels.com", "Booking": "", "IG": "freehandchicago", "Why": "Ultra-hip, meticulously stylized bohemian decor blending extreme dark wood with vivid, vintage South American textiles.", "Capacity": "100"},
    {"Name": "The Allerton Hotel (Tip Top Tap - Abandoned Feel)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Near North Side", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "warwickallerton", "Why": "A legendary, long-closed 1940s skyscraper lounge that still intensely radiates Sinatra-era ghost vibes high above the city.", "Capacity": "Varies"},
    {"Name": "St. Ignatius College Prep (Tully Hall)", "Type": "Indoor", "Category": "library", "Neighborhood": "Near West Side", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "stignatiuschicago", "Why": "Impeccably preserved 1870s woodwork and towering arched bookcases make this feel like a deep academic sanctuary.", "Capacity": "Varies"},
    {"Name": "Lane Tech College Prep (Auditorium & Murals)", "Type": "Indoor", "Category": "theater", "Neighborhood": "Roscoe Village", "Feasibility": 4, "Contact": "", "Booking": "", "IG": "", "Why": "A gigantic, 2,000-seat public school auditorium heavily lined with absolutely massive New Deal-era WPA fresco murals.", "Capacity": "Varies"},
    {"Name": "Schurz High School (Prairie Style Interior)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Irving Park", "Feasibility": 4, "Contact": "", "Booking": "", "IG": "", "Why": "An architectural rarity; an entire colossal public high school fully embodying Frank Lloyd Wright's prairie aesthetic.", "Capacity": "Varies"},
    {"Name": "Fourth Presbyterian Church (Sanctuary)", "Type": "Indoor", "Category": "church", "Neighborhood": "Streeterville", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "fourthpreschicago", "Why": "Monolithic Gothic Revival stone pillars climbing to a stunning, dramatically sloped carved wooden ceiling.", "Capacity": "Varies"},
    {"Name": "St. Hedwig Catholic Church", "Type": "Indoor", "Category": "church", "Neighborhood": "Bucktown", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "Astonishingly ornate 'Polish Cathedral' style emphasizing deep gold trim and intensely vivid stained glass.", "Capacity": "Varies"},
    {"Name": "Our Lady of Mount Carmel Church", "Type": "Indoor", "Category": "church", "Neighborhood": "Lakeview", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "ourladyofmountcarmelchi", "Why": "Deep reds and intense wood paneling provide a much tighter, more visceral gothic feeling than larger cathedrals.", "Capacity": "Varies"},
    {"Name": "Rockefeller Memorial Chapel (Main Nave)", "Type": "Indoor", "Category": "church", "Neighborhood": "Hyde Park", "Feasibility": 6, "Contact": "events@uchicago.edu", "Booking": "", "IG": "ucrockefeller", "Why": "Towering, brooding stone walls culminating in a terrifyingly massive Gothic vaulted ceiling that dominates the university.", "Capacity": "Varies"},
    {"Name": "Epiphany Center for the Arts (Catacombs)", "Type": "Indoor", "Category": "adaptive reuse", "Neighborhood": "West Loop", "Feasibility": 9, "Contact": "events@epiphanychi.com", "Booking": "epiphanychi.com", "IG": "epiphanyartscenter", "Why": "A rugged, completely subterranean stone basement with ultra-low ceilings and moody track lighting.", "Capacity": "100"},
    {"Name": "Bridgeport Art Center (Sculpture Garden Gallery)", "Type": "Indoor", "Category": "gallery", "Neighborhood": "Bridgeport", "Feasibility": 9, "Contact": "events@bridgeportart.com", "Booking": "bridgeportart.com", "IG": "bridgeportartcenter", "Why": "An endlessly long, stark white corridor heavily lined with monolithic raw structural wood columns.", "Capacity": "Varies"},
    {"Name": "Renaissance Society", "Type": "Indoor", "Category": "gallery", "Neighborhood": "Hyde Park", "Feasibility": 6, "Contact": "info@renaissancesociety.org", "Booking": "", "IG": "rensociety", "Why": "A high, stark, dramatically lit vaulted gallery hidden completely inside one of the campus's oldest gothic buildings.", "Capacity": "Varies"},
    {"Name": "Space 1858", "Type": "Indoor", "Category": "storefront", "Neighborhood": "West Town", "Feasibility": 10, "Contact": "info@space1858.com", "Booking": "space1858.com", "IG": "space1858", "Why": "An aggressively simple, hyper-clean white box storefront designed specifically for total photographic control.", "Capacity": "40"},
    {"Name": "Ed Debevic's (Retro Diner Interior)", "Type": "Indoor", "Category": "restaurant", "Neighborhood": "Streeterville", "Feasibility": 7, "Contact": "", "Booking": "", "IG": "eddebevics", "Why": "A completely overwhelming, neon-drenched sensory overload perfectly mimicking a 1950s retro diner aesthetic.", "Capacity": "150"},
    {"Name": "Margie's Candies (Vintage Ice Cream Parlor)", "Type": "Indoor", "Category": "restaurant", "Neighborhood": "Logan Square", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "", "Why": "Completely untouched 1920s interior featuring tiny booths, ancient Tiffany lamps, and peeling vintage sweetness.", "Capacity": "30"},
    {"Name": "The Berghoff (Historic Dining Room)", "Type": "Indoor", "Category": "restaurant", "Neighborhood": "Loop", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "berghoffchicago", "Why": "An endless sea of dark mahogany, stained glass, and terrifyingly efficient German pub aesthetics.", "Capacity": "Varies"},
    {"Name": "Walnut Room (Macy's State Street)", "Type": "Indoor", "Category": "restaurant", "Neighborhood": "Loop", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "Circassian walnut paneling and towering ceilings provide an intensely regal, old-world department store grandeur.", "Capacity": "Varies"},
    {"Name": "Cherry Circle Room (CAA)", "Type": "Indoor", "Category": "restaurant", "Neighborhood": "Loop", "Feasibility": 8, "Contact": "", "Booking": "", "IG": "cherrycircleroom", "Why": "A windowless, intimately dark, wildly stylized mid-century modern dining room feeling like a perfect Mad Men set.", "Capacity": "60"},
    {"Name": "Museum of Contemporary Art (Interior Stairwell)", "Type": "Indoor", "Category": "museum", "Neighborhood": "Streeterville", "Feasibility": 6, "Contact": "events@mcachicago.org", "Booking": "", "IG": "mcachicago", "Why": "A violently sharp, intensely white minimalist spiral staircase that physically mimics the inside of a nautilus shell.", "Capacity": "Varies"},
    {"Name": "National Museum of Puerto Rican Arts and Culture", "Type": "Indoor", "Category": "museum", "Neighborhood": "Humboldt Park", "Feasibility": 7, "Contact": "info@nmprac.org", "Booking": "", "IG": "nmprac", "Why": "Exhibits housed inside a dramatically gorgeous Queen Anne-style former stable building deep inside the park.", "Capacity": "100"},
    {"Name": "Ed Paschke Art Center", "Type": "Indoor", "Category": "museum", "Neighborhood": "Jefferson Park", "Feasibility": 8, "Contact": "info@edpaschkeartcenter.org", "Booking": "", "IG": "edpaschkeartcenter", "Why": "Hyper-colored, neon-saturated pop-art galleries explicitly contrasting with an austere stone architectural shell.", "Capacity": "80"},
    {"Name": "Copernicus Center", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Jefferson Park", "Feasibility": 7, "Contact": "events@copernicuscenter.org", "Booking": "", "IG": "copernicuscenter", "Why": "A massive, dizzying starry sky ceiling set over an eccentric mix of 1930s cinematic architecture and Polish motifs.", "Capacity": "Varies"},
    {"Name": "Heritage Museum of Asian Art", "Type": "Indoor", "Category": "museum", "Neighborhood": "Bridgeport", "Feasibility": 8, "Contact": "info@heritageasianart.org", "Booking": "", "IG": "heritageasianart", "Why": "A pristine, totally quiet atmosphere featuring extreme wooden geometric screens framing ancient jade and pottery.", "Capacity": "Varies"},
    {"Name": "McCormick Bridgehouse (Gear Rooms)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Loop", "Feasibility": 7, "Contact": "bridgehousemuseum@chicagoriver.org", "Booking": "", "IG": "bridgehousemuseum", "Why": "Deep within the river tower, entirely consumed by terrifyingly massive, greasy interlocked steel bridge gears.", "Capacity": "40"},
    {"Name": "Macy's on State Street (Tiffany Vaulted Ceiling)", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "The absolute largest continuous piece of Favrile glass in the world, glowing intensely above retail floors.", "Capacity": "Varies"},
    {"Name": "Garfield Park Conservatory (Palm House)", "Type": "Indoor", "Category": "immersive exhibit", "Neighborhood": "East Garfield Park", "Feasibility": 8, "Contact": "rentals@garfieldpark.org", "Booking": "", "IG": "garfieldparkconservatory", "Why": "A staggering 65-foot-high glass ceiling barely containing an incredibly dense, chaotic explosion of tropical palms.", "Capacity": "Varies"},
    {"Name": "Lincoln Park Conservatory (Fern Room)", "Type": "Indoor", "Category": "immersive exhibit", "Neighborhood": "Lincoln Park", "Feasibility": 7, "Contact": "", "Booking": "", "IG": "lincolnparkconservancy", "Why": "A sunken, extremely humid prehistoric environment heavily rooted with giant ferns and ancient cycads.", "Capacity": "40"},
    {"Name": "Field Museum (Grainger Hall of Gems)", "Type": "Indoor", "Category": "museum", "Neighborhood": "Near South Side", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "fieldmuseum", "Why": "A completely blackened, mirrored room explicitly designed to make thousands of jewels aggressively glow in the dark.", "Capacity": "Varies"},
    {"Name": "Museum of Science and Industry (Whispering Gallery)", "Type": "Indoor", "Category": "museum", "Neighborhood": "Hyde Park", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "msichicago", "Why": "A weird, acoustically perfect dome structure offering terrifying sound isolation and minimalist geometric beauty.", "Capacity": "Varies"},
    {"Name": "Shedd Aquarium (Caribbean Reef Rotunda)", "Type": "Indoor", "Category": "museum", "Neighborhood": "Near South Side", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "shedd_aquarium", "Why": "An impossibly massive, glowing blue column of 90,000 gallons of water completely dominating a marble hall.", "Capacity": "Varies"},
    {"Name": "Adler Planetarium (Doane Observatory)", "Type": "Indoor", "Category": "museum", "Neighborhood": "Near South Side", "Feasibility": 7, "Contact": "events@adlerplanetarium.org", "Booking": "", "IG": "adlerplanet", "Why": "A stark white, harshly brutalist geometric dome housing the largest aperture telescope accessible to the public.", "Capacity": "50"},
    {"Name": "Chicago Architecture Center (Drake Skyscraper Gallery)", "Type": "Indoor", "Category": "museum", "Neighborhood": "Loop", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "chiarchitecture", "Why": "A towering wall featuring dozens of impossibly detailed, suspended scale models of world-famous skyscrapers.", "Capacity": "Varies"},
    {"Name": "Driehaus Museum (Smirnoff Room)", "Type": "Indoor", "Category": "museum", "Neighborhood": "Near North Side", "Feasibility": 6, "Contact": "events@driehausmuseum.org", "Booking": "", "IG": "driehausmuseum", "Why": "Completely covered floor-to-ceiling in intensely vibrant, overwhelming blue Lincrusta wallpaper and mahogany.", "Capacity": "30"},
    {"Name": "Chicago Board of Trade (Ceres Lobby)", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "cbotbuilding", "Why": "An impossibly slick, three-story Art Deco lobby bathed in contrasting black and light-grey marble.", "Capacity": "Varies"},
    {"Name": "The Monadnock Building (Aluminum & Glass Entrances)", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "A rare transitional space where intensely heavy masonry dramatically gives way to sleek, highly polished aluminum stairs.", "Capacity": "Varies"},
    {"Name": "Tribune Tower (Hall of Inscriptions)", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Near North Side", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "", "Why": "A deeply shadowed, incredibly grim passageway completely carved with monumental text.", "Capacity": "Varies"},
    {"Name": "The Carbide & Carbon Building (Elevator Banks)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Loop", "Feasibility": 7, "Contact": "", "Booking": "", "IG": "", "Why": "Dripping with intensely dark black granite and wildly excessive gold-leaf Art Deco geometric trims.", "Capacity": "Varies"},
    {"Name": "Chicago Architecture Center (Main Arcade)", "Type": "Indoor", "Category": "museum", "Neighborhood": "Loop", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "Mies van der Rohe's masterpiece lobby heavily featuring radically exposed, massive black steel pilotis.", "Capacity": "Varies"},
    {"Name": "The Robey (Lounge & Tower)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Wicker Park", "Feasibility": 8, "Contact": "", "Booking": "", "IG": "therobeychicago", "Why": "Intensely triangular floor-plates forcing weird, angular interior geometry overlooking the Six Corners chaos.", "Capacity": "Varies"},
    {"Name": "The Drake Hotel (French Room)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Gold Coast", "Feasibility": 7, "Contact": "", "Booking": "", "IG": "thedrakehotel", "Why": "An overwhelmingly ornate, relatively small parlor room heavily drowning in baroque wood and floral excess.", "Capacity": "80"},
    {"Name": "St. Josaphat Parish", "Type": "Indoor", "Category": "church", "Neighborhood": "Lincoln Park", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "A stunning, massive Romanesque basilica explicitly characterized by incredibly harsh, heavy raw brick pillars.", "Capacity": "Varies"},
    {"Name": "St. Hyacinth Basilica", "Type": "Indoor", "Category": "church", "Neighborhood": "Avondale", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "One of only three minor basilicas in the city, an absolutely monumental and dizzyingly frescoed Polish cathedral.", "Capacity": "Varies"},
    {"Name": "St. Mary of Perpetual Help", "Type": "Indoor", "Category": "church", "Neighborhood": "Bridgeport", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "Heavily adorned Byzantine-Romanesque interior featuring an incredibly vibrant, overwhelming central dome.", "Capacity": "Varies"},
    {"Name": "First Presbyterian Church of Chicago", "Type": "Indoor", "Category": "church", "Neighborhood": "Woodlawn", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "An incredibly stark, almost fortress-like Gothic brick exterior hiding a deeply somber, cavernous wooden nave.", "Capacity": "Varies"},
    {"Name": "First United Methodist Church (Sanctuary)", "Type": "Indoor", "Category": "church", "Neighborhood": "Loop", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "chicagotemple", "Why": "A terrifyingly massive, fiercely gothic sanctuary completely hidden entirely within the first floors of a skyscraper.", "Capacity": "Varies"},
    {"Name": "Holy Family Church", "Type": "Indoor", "Category": "church", "Neighborhood": "Near West Side", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "The absolute oldest surviving wood-carved church interior in Chicago, feeling deeply ancient and highly flammable.", "Capacity": "Varies"},
    {"Name": "The Shrine of Christ the King Sovereign Priest", "Type": "Indoor", "Category": "ruin", "Neighborhood": "Woodlawn", "Feasibility": 3, "Contact": "", "Booking": "", "IG": "", "Why": "An absolutely surreal, actively stabilizing post-fire church ruin functioning visually as a grand open-air stone monument.", "Capacity": "Varies"},
    {"Name": "Ebenezer Missionary Baptist Church", "Type": "Indoor", "Category": "church", "Neighborhood": "Bronzeville", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "An iconic, profoundly resonant auditorium-style sanctuary crucial to the absolute invention of gospel music.", "Capacity": "Varies"},
    {"Name": "Nativity of Our Lord Catholic Church", "Type": "Indoor", "Category": "church", "Neighborhood": "Bridgeport", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "Featuring impossibly pristine white altars sharply contrasting heavily with deep, dark wooden pews.", "Capacity": "Varies"},
    {"Name": "Co-Prosperity Sphere", "Type": "Indoor", "Category": "gallery", "Neighborhood": "Bridgeport", "Feasibility": 9, "Contact": "info@publicmediainstitute.com", "Booking": "", "IG": "coprosperitychicago", "Why": "A deeply experimental, aggressively windowed street-level exhibition space that feels incredibly raw and visceral.", "Capacity": "100"},
    {"Name": "Bridgeport Art Center (Maritime Gallery)", "Type": "Indoor", "Category": "gallery", "Neighborhood": "Bridgeport", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "bridgeportartcenter", "Why": "Completely stripped, impossibly wide lower-level industrial floors deeply set among structural brick.", "Capacity": "Varies"},
    {"Name": "Chicago Art Department", "Type": "Indoor", "Category": "gallery", "Neighborhood": "Pilsen", "Feasibility": 8, "Contact": "info@chicagoartdepartment.org", "Booking": "", "IG": "chicagoartdept", "Why": "A deeply gritty, intensely active multi-room artist studio heavily defined by battered floors and vibrant walls.", "Capacity": "Varies"},
    {"Name": "Morgan Arts Complex", "Type": "Indoor", "Category": "gallery", "Neighborhood": "Bridgeport", "Feasibility": 9, "Contact": "events@morganartscomplex.com", "Booking": "", "IG": "morganartscomplex", "Why": "Massive, wildly refined post-industrial gallery leaning heavily into pristine white walls and stark iron accents.", "Capacity": "Varies"},
    {"Name": "Stan Mansion", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Logan Square", "Feasibility": 9, "Contact": "info@stanmansion.com", "Booking": "stanmansion.com", "IG": "stanmansion", "Why": "An imposingly grand, completely restored Masonic lodge heavily utilizing dramatic lighting and towering arches.", "Capacity": "300"},
    {"Name": "Rockwell on the River", "Type": "Indoor", "Category": "warehouse", "Neighborhood": "Avondale", "Feasibility": 10, "Contact": "events@rockwellontheriver.com", "Booking": "rockwellontheriver.com", "IG": "rockwellontheriver", "Why": "A fiercely angular, bow-truss timber roof over completely raw concrete floors directly adjacent to the river.", "Capacity": "Varies"},
    {"Name": "Room 1520", "Type": "Indoor", "Category": "loft", "Neighborhood": "West Loop", "Feasibility": 10, "Contact": "info@room1520.com", "Booking": "room1520.com", "IG": "room1520", "Why": "A meticulously minimal, starkly white historical gear-factory loft completely flooded with harsh natural light.", "Capacity": "150"},

    # OUTDOOR
    {"Name": "Crown Fountain (Glass Brick Underbelly)", "Type": "Outdoor", "Category": "public art", "Neighborhood": "Loop", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "Focusing completely on the brutalist, highly repetitive glass brick monolithic sides rather than the spitting faces.", "Capacity": "Varies"},
    {"Name": "Maggie Daley Park (Play Garden Towers)", "Type": "Outdoor", "Category": "park", "Neighborhood": "Loop", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "Bizarre, terrifyingly large metallic suspension bridges and eccentric nautical towers meant for kids but striking on film.", "Capacity": "Varies"},
    {"Name": "Grant Park (Agora Sculptures)", "Type": "Outdoor", "Category": "public art", "Neighborhood": "South Loop", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "106 impossibly huge, headless, rusting iron bodies violently frozen mid-stride across an empty plaza.", "Capacity": "Varies"},
    {"Name": "Buckingham Fountain (Off-season/Empty)", "Type": "Outdoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 8, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "When drained and dry, the massive pink marble basins feel like a surreal, completely desolate ancient ruin.", "Capacity": "Varies"},
    {"Name": "Navy Pier (East End Plaza / Wave Wall)", "Type": "Outdoor", "Category": "architectural landmark", "Neighborhood": "Streeterville", "Feasibility": 8, "Contact": "navypierinfo@navypier.org", "Booking": "", "IG": "", "Why": "Far past the tourist traps, a fiercely modernist, heavily sweeping staircase leading straight into terrifying lake oblivion.", "Capacity": "Varies"},
    {"Name": "Chicago Riverwalk (The Cove)", "Type": "Outdoor", "Category": "waterfront", "Neighborhood": "Loop", "Feasibility": 9, "Contact": "chicagoriverwalk@cityofchicago.org", "Booking": "", "IG": "", "Why": "Extremely low-profile concrete seating literally hovering inches above the terrifyingly deep green river water.", "Capacity": "Varies"},
    {"Name": "Ping Tom Memorial Park (Pagoda Pavilion)", "Type": "Outdoor", "Category": "park", "Neighborhood": "Chinatown", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "A spectacularly bright, deeply traditional red pavilion completely surrounded by brutal railroad rust.", "Capacity": "Varies"},
    {"Name": "The 606 (Walnut Street Curve)", "Type": "Outdoor", "Category": "park", "Neighborhood": "Logan Square", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "the606chicago", "Why": "A dramatically sloping, highly angular concrete path that forces the entire urban skyline perfectly into frame.", "Capacity": "Varies"},
    {"Name": "Palmisano Park (Stearns Quarry Mound)", "Type": "Outdoor", "Category": "park", "Neighborhood": "Bridgeport", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "A terrifyingly steep, completely manufactured grassy hill providing an isolated, windy plateau overlooking the south side.", "Capacity": "Varies"},
    {"Name": "Northerly Island (Adler Planetarium Skyline Walk)", "Type": "Outdoor", "Category": "nature preserve", "Neighborhood": "Near South Side", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "A violently sweeping, completely unobstructed curving path that makes the city look like a distant island.", "Capacity": "Varies"},
    {"Name": "Promontory Point (Fire Pits)", "Type": "Outdoor", "Category": "waterfront", "Neighborhood": "Hyde Park", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "Deep concrete council rings built directly into the terrifyingly steep limestone drops into the lake.", "Capacity": "Varies"},
    {"Name": "Jackson Park (Osaka Garden Moon Bridge)", "Type": "Outdoor", "Category": "garden", "Neighborhood": "Hyde Park", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "A completely isolated, intensely arched wooden bridge deeply shrouded within absolutely wild, unkempt weeping willows.", "Capacity": "Varies"},
    {"Name": "Washington Park (Bulls Eye)", "Type": "Outdoor", "Category": "park", "Neighborhood": "Washington Park", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "A completely bizarre, perfectly circular grassy amphitheater depression deeply carved into a massive field.", "Capacity": "Varies"},
    {"Name": "Garfield Park (Bandstand)", "Type": "Outdoor", "Category": "park", "Neighborhood": "East Garfield Park", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "A beautifully decaying, incredibly ornate marble outdoor gazebo completely adrift atop a small lagoon island.", "Capacity": "Varies"},
    {"Name": "Humboldt Park (Boathouse Pavilion Exterior)", "Type": "Outdoor", "Category": "park", "Neighborhood": "Humboldt Park", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "Sweeping, wildly romantic Prairie style exterior terraces leading down to incredibly still, heavily shaded water.", "Capacity": "Varies"},
    {"Name": "Douglas Park (Flower Garden)", "Type": "Outdoor", "Category": "garden", "Neighborhood": "North Lawndale", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "Intensely structured, heavily layered geometric pathways deeply sunken into a surrounding wild woodland.", "Capacity": "Varies"},
    {"Name": "Columbus Park (Waterfalls)", "Type": "Outdoor", "Category": "nature preserve", "Neighborhood": "Austin", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "An absolutely surreal, beautifully manufactured cascading stone waterfall completely hidden inside an urban park.", "Capacity": "Varies"},
    {"Name": "Marquette Park (Lagoon Islands)", "Type": "Outdoor", "Category": "park", "Neighborhood": "Chicago Lawn", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "Densely wooded, incredibly isolated micro-islands completely ringed by beautifully overgrown algae-covered banks.", "Capacity": "Varies"},
    {"Name": "Lincoln Park (Alfred Caldwell Lily Pool circular stone)", "Type": "Outdoor", "Category": "garden", "Neighborhood": "Lincoln Park", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "A specifically stark, deeply shadowed completely circular stone pavilion fiercely guarding a hidden lagoon.", "Capacity": "Varies"},
    {"Name": "Lincoln Park Zoo (Rookery)", "Type": "Outdoor", "Category": "architectural landmark", "Neighborhood": "Lincoln Park", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "An intensely eerie, completely overgrown island entirely coated with hundreds of nesting, screaming herons.", "Capacity": "Varies"},
    {"Name": "Goudy Square Park", "Type": "Outdoor", "Category": "park", "Neighborhood": "Gold Coast", "Feasibility": 10, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "An impossibly tiny, incredibly ornate micro-park completely dominated by massive, looming brick high-rises.", "Capacity": "Varies"},
    {"Name": "Senn Park", "Type": "Outdoor", "Category": "park", "Neighborhood": "Edgewater", "Feasibility": 10, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "Fiercely geometric, deeply manicured green spaces leading directly to an incredibly imposing, massive high school facade.", "Capacity": "Varies"},
    {"Name": "Indian Boundary Park (Tudor Fieldhouse Exterior)", "Type": "Outdoor", "Category": "historic building", "Neighborhood": "West Ridge", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "A completely absurd, highly detailed Tudor-style mansion structure bizarrely dropped straight into a public park.", "Capacity": "Varies"},
    {"Name": "Clarendon Park Community Center (Exterior)", "Type": "Outdoor", "Category": "historic building", "Neighborhood": "Uptown", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "An intensely grand, heavily columned brick structure completely surrounded by completely barren sporting fields.", "Capacity": "Varies"},
    {"Name": "Winnemac Park (Prairie Grasslands)", "Type": "Outdoor", "Category": "nature preserve", "Neighborhood": "Lincoln Square", "Feasibility": 10, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "Acres of totally wild, highly aggressive tallgrass prairie completely hiding the surrounding neighborhood grid.", "Capacity": "Varies"},
    {"Name": "Horner Park (Riverfront Trail)", "Type": "Outdoor", "Category": "nature preserve", "Neighborhood": "Irving Park", "Feasibility": 10, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "A freshly eroded, entirely wild dirt path incredibly close to the rushing, muddy north branch river waters.", "Capacity": "Varies"},
    {"Name": "River Park (Dam/Waterfall)", "Type": "Outdoor", "Category": "nature preserve", "Neighborhood": "Albany Park", "Feasibility": 10, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "An intensely loud, completely brutal concrete dam structure where the river wildly drops several feet in elevation.", "Capacity": "Varies"},
    {"Name": "North Park Village Nature Center", "Type": "Outdoor", "Category": "nature preserve", "Neighborhood": "North Park", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "An absolutely surreal, utterly silent deer-filled woodland completely erased from the surrounding dense city.", "Capacity": "Varies"},
    {"Name": "Lakeshore Drive Tunnel (Addison)", "Type": "Outdoor", "Category": "public art", "Neighborhood": "Lakeview", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "A terrifyingly long, intensely colorful mosaic-tiled pedestrian tube deeply buried under roaring speedways.", "Capacity": "Varies"},
    {"Name": "Oakwood Beach", "Type": "Outdoor", "Category": "waterfront", "Neighborhood": "Kenwood", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "An incredibly wide, completely desolate beach expanse completely shadowed by deep brutalist concrete breakwaters.", "Capacity": "Varies"}
]

def load_memory():
    memory = set()
    if os.path.exists(MEMORY_FILE):
        with open(MEMORY_FILE, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                memory.add(row['Location Name'].lower().strip())
    return memory

def write_memory(new_locations):
    file_exists = os.path.exists(MEMORY_FILE)
    with open(MEMORY_FILE, 'a', encoding='utf-8', newline='') as f:
        fieldnames = ['Location Name', 'Type', 'Space Category', 'Neighborhood', 'Feasibility Score', 'Contact Info', 'Booking Link', 'IG/Social Link', 'Why It\'s Interesting', 'Capacity Estimate']
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        if not file_exists:
            writer.writeheader()
        for loc in new_locations:
            writer.writerow(loc)

def main():
    memory = load_memory()
    
    unique_locations = []
    
    for loc in locations:
        loc_name = loc['Name'].lower().strip()
        if loc_name not in memory:
            row = {
                'Location Name': loc['Name'],
                'Type': loc['Type'],
                'Space Category': loc['Category'],
                'Neighborhood': loc['Neighborhood'],
                'Feasibility Score': loc['Feasibility'],
                'Contact Info': loc['Contact'],
                'Booking Link': loc['Booking'],
                'IG/Social Link': loc['IG'],
                'Why It\'s Interesting': loc['Why'],
                'Capacity Estimate': loc['Capacity']
            }
            unique_locations.append(row)
            
    print(f"Sourced {len(unique_locations)} unique locations.")
    print(f"Number of duplicates rejected: {len(locations) - len(unique_locations)}")
    
    with open(OUTPUT_FILE, 'w', encoding='utf-8', newline='') as f:
        fieldnames = ['Location Name', 'Type', 'Space Category', 'Neighborhood', 'Feasibility Score', 'Contact Info', 'Booking Link', 'IG/Social Link', 'Why It\'s Interesting', 'Capacity Estimate']
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(unique_locations)
        
    print(f"Run data written to {OUTPUT_FILE}")
    
    write_memory(unique_locations)
    print("Memory updated successfully.")

if __name__ == '__main__':
    main()
