import csv
import json
import os

MEMORY_FILE = 'scout_memory.csv'
OUTPUT_FILE = 'locations_run_3.csv'


locations = [
    # INDOOR
    {"Name": "The Hideout (Daytime Historic Structure/Exterior)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Noble Square", "Feasibility": 7, "Contact": "booking@hideoutchicago.com", "Booking": "hideoutchicago.com", "IG": "hideoutchicago", "Why": "A literal balloon-frame 19th-century house surrounded in an industrial snowplow graveyard; fascinating during off-hours.", "Capacity": "50"},
    {"Name": "Elks National Memorial Building (Rotunda)", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Lincoln Park", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "elksmemorial", "Why": "Features one of the most stunning, overwhelmingly massive and ornate marble domes in the entire country.", "Capacity": "150"},
    {"Name": "James R. Thompson Center (Hollow Atrium)", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "A postmodern, massive spaceship-like glass atrium offering insane interior lines and scale.", "Capacity": "Varies"},
    {"Name": "Aon Center (70th Floor Empty Space)", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 4, "Contact": "events@aoncenter.info", "Booking": "", "IG": "", "Why": "Completely empty, raw high-rise skyscraper floor offering panoramic, unobstructed 360-degree concrete and glass views.", "Capacity": "Varies"},
    {"Name": "Fine Arts Building (The Dial Bookshop)", "Type": "Indoor", "Category": "store", "Neighborhood": "Loop", "Feasibility": 7, "Contact": "info@dialbookshop.com", "Booking": "", "IG": "dialbookshop", "Why": "Overlooking Michigan Ave, packed with floor-to-ceiling vintage books and bathed in dark woods and warm light.", "Capacity": "30"},
    {"Name": "Fine Arts Building (10th Floor Mural Corridors)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Loop", "Feasibility": 7, "Contact": "", "Booking": "", "IG": "fineartsbuilding", "Why": "Ancient, incredibly well-preserved painted murals flank a very narrow, moody 19th-century hallway.", "Capacity": "Varies"},
    {"Name": "The Rookery Building (Oriel Staircase)", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 6, "Contact": "events@therookerybuilding.com", "Booking": "https://therookerybuilding.com", "IG": "therookerybuilding", "Why": "A terrifyingly beautiful, spiraling wrought-iron staircase that looks suspended completely in mid-air.", "Capacity": "Varies"},
    {"Name": "Garfield Park Conservatory (Desert House)", "Type": "Indoor", "Category": "immersive exhibit", "Neighborhood": "East Garfield Park", "Feasibility": 8, "Contact": "rentals@garfieldpark.org", "Booking": "", "IG": "garfieldparkconservatory", "Why": "Stark sand and massive, looming, alien-like cacti and succulents under geometric glass.", "Capacity": "100"},
    {"Name": "Ling Shen Ching Tze Temple", "Type": "Indoor", "Category": "church", "Neighborhood": "Bridgeport", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "A majestic multi-level Buddhist temple housed confusingly inside an old Presbyterian church brick facade.", "Capacity": "100"},
    {"Name": "Roosevelt University Library (Auditorium Building Reading Room)", "Type": "Indoor", "Category": "library", "Neighborhood": "Loop", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "rooseveltulibrary", "Why": "Colossal arches, warm woods, and historic stenciling overlooking the lake in a heavily silent atmosphere.", "Capacity": "100"},
    {"Name": "190 South LaSalle (The Lobby Library)", "Type": "Indoor", "Category": "library", "Neighborhood": "Loop", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "", "Why": "Features dramatic, overpowering multi-story gold vaulted ceilings casting a dark, glowing ambiance.", "Capacity": "Varies"},
    {"Name": "311 South Wacker (Winter Garden)", "Type": "Indoor", "Category": "immersive exhibit", "Neighborhood": "Loop", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "Massive palm trees surround a glowing, surreal luminescent fountain inside a vast glass enclosure.", "Capacity": "Varies"},
    {"Name": "Lakeside Center at McCormick Place (East Building Empty Glass Halls)", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Near South Side", "Feasibility": 4, "Contact": "sales@mccormickplace.com", "Booking": "", "IG": "mccormickplace", "Why": "Colossal, echoing empty convention halls heavily bordered by brutal black steel and an endless lake horizon.", "Capacity": "Varies"},
    {"Name": "Nichols Tower at Homan Square (Top Floor Event Space)", "Type": "Indoor", "Category": "adaptive reuse", "Neighborhood": "North Lawndale", "Feasibility": 8, "Contact": "info@fshn.org", "Booking": "", "IG": "", "Why": "The 14th-floor observatory of the original 1905 Sears Tower featuring arched windows and stark urban views.", "Capacity": "50"},
    {"Name": "South Shore Cultural Center (Paul Robeson Theater)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "South Shore", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "", "Why": "An abandoned-feeling, highly ornate historic theater showing dramatic signs of layered, beautiful neglect.", "Capacity": "150"},
    {"Name": "The Forum", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Bronzeville", "Feasibility": 7, "Contact": "info@theforumbronzeville.com", "Booking": "", "IG": "theforumbronzeville", "Why": "An 1889 assembly hall under slow restoration, revealing unbelievable layers of peeling wallpaper and history.", "Capacity": "150"},
    {"Name": "The Wabash YMCA (Bronzeville - historic gym/pool)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Bronzeville", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "Historically significant Renaissance Revival structure featuring a long-empty old-world gymnasium.", "Capacity": "100"},
    {"Name": "The Anthony Overton Elementary School", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Bronzeville", "Feasibility": 7, "Contact": "", "Booking": "", "IG": "overtonuninc", "Why": "A highly striking abandoned modernist school heavily repurposed for chaotic, colorful art installations.", "Capacity": "Varies"},
    {"Name": "The Chicago Board Options Exchange (Trading Floor)", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 3, "Contact": "", "Booking": "", "IG": "", "Why": "Absolutely chaotic and massive brutalist architecture filled with outdated tech when completely empty.", "Capacity": "Varies"},
    {"Name": "The Old Post Office (The Telegram Lounge)", "Type": "Indoor", "Category": "adaptive reuse", "Neighborhood": "Loop", "Feasibility": 8, "Contact": "events@post433.com", "Booking": "", "IG": "post433", "Why": "A mid-century brutalist vibe featuring moody lighting, low leather couches, and geometric ceilings.", "Capacity": "80"},
    {"Name": "Water Tower Pumping Station (Interior pipes)", "Type": "Indoor", "Category": "industrial", "Neighborhood": "River North", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "", "Why": "A subterranean limestone structure containing intensely loud, multi-story active blue steel water pumps.", "Capacity": "Varies"},
    {"Name": "Harold Washington Library (The 9th Floor Gallery)", "Type": "Indoor", "Category": "library", "Neighborhood": "Loop", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "chipublib", "Why": "Highly angular, imposing geometric hallways entirely dominated by intense, severe red lighting and metal panels.", "Capacity": "Varies"},
    {"Name": "Newberry Library (The Retiring Room)", "Type": "Indoor", "Category": "library", "Neighborhood": "Near North Side", "Feasibility": 6, "Contact": "events@newberry.org", "Booking": "", "IG": "newberrylibrary", "Why": "An anachronistic, highly stylized, dark Victorian parlor explicitly designed for absolute quiet.", "Capacity": "20"},
    {"Name": "Madonna della Strada Chapel (Loyola Univ)", "Type": "Indoor", "Category": "church", "Neighborhood": "Rogers Park", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "loyolachicago", "Why": "Stunning Art Deco maritime-influenced church perched literally on the violent edge of the lake.", "Capacity": "150"},
    {"Name": "University of Chicago (Harper Memorial Library Reading Room)", "Type": "Indoor", "Category": "library", "Neighborhood": "Hyde Park", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "uchicagolibrary", "Why": "Hogwarts-esque towering limestone arches framing massive chandeliers and an unending sea of dark wood.", "Capacity": "Varies"},
    {"Name": "University of Chicago (Bond Chapel)", "Type": "Indoor", "Category": "church", "Neighborhood": "Hyde Park", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "Tiny, intensely intricate and heavily wooded Gothic chapel overflowing with dark, detailed stained glass.", "Capacity": "40"},
    {"Name": "The Blackstone Hotel (Crystal Ballroom)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "South Loop", "Feasibility": 7, "Contact": "", "Booking": "", "IG": "theblackstonehotel", "Why": "An oppressively ornate Beaux-Arts ballroom featuring heavy drapery and excessive crystal.", "Capacity": "200"},
    {"Name": "The Congress Plaza Hotel (Gold Room)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Loop", "Feasibility": 7, "Contact": "", "Booking": "", "IG": "", "Why": "Infamously haunted ballroom featuring bizarrely ornate, almost decaying golden plasterwork.", "Capacity": "250"},
    {"Name": "The Drake Hotel (Palm Court)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Gold Coast", "Feasibility": 7, "Contact": "", "Booking": "", "IG": "thedrakehotel", "Why": "Vast, opulent tea room dominated by an enormous, intricately carved limestone fountain.", "Capacity": "100"},
    {"Name": "The Reliance Building (Stairwell/Lobby)", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "The first skyscraper to use large plate glass, creating highly disorienting, stark white terra cotta interiors.", "Capacity": "Varies"},
    {"Name": "The Woman's Athletic Club", "Type": "Indoor", "Category": "private club", "Neighborhood": "Near North Side", "Feasibility": 3, "Contact": "", "Booking": "", "IG": "", "Why": "An impossible to penetrate fortress of perfectly preserved 1920s French-influenced excess.", "Capacity": "100"},
    {"Name": "The Union League Club of Chicago (Library)", "Type": "Indoor", "Category": "private club", "Neighborhood": "Loop", "Feasibility": 4, "Contact": "", "Booking": "", "IG": "ulcchicago", "Why": "A profoundly quiet, old-money multi-story library stacked end to end with rare books and oil portraits.", "Capacity": "100"},
    {"Name": "The Chicago Athletic Association (White City Ballroom)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Loop", "Feasibility": 7, "Contact": "events@chicagoathletichotel.com", "Booking": "", "IG": "chicagoathletichotel", "Why": "Features stalactite-like plaster ceilings and enormous gothic fireplaces overlooking the park.", "Capacity": "250"},
    {"Name": "The Fisher Building (Lobby)", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "A bizarre, neo-gothic lobby densely packed with yellow terra cotta carvings of mythical aquatic creatures.", "Capacity": "Varies"},
    {"Name": "The Manhattan Building (Lobby)", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "", "Why": "One of the oldest surviving steel-framed skyscrapers, featuring extremely dark, claustrophobic granite halls.", "Capacity": "Varies"},
    {"Name": "The McCormick Place (Underground busways)", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Near South Side", "Feasibility": 3, "Contact": "", "Booking": "", "IG": "", "Why": "Endless, echoing, brightly lit concrete tunnels running for miles beneath the convention centers.", "Capacity": "Varies"},
    {"Name": "Museum of Science and Industry (The Coal Mine exhibit)", "Type": "Indoor", "Category": "immersive exhibit", "Neighborhood": "Hyde Park", "Feasibility": 4, "Contact": "specialevents@msichicago.org", "Booking": "", "IG": "msichicago", "Why": "A painstakingly recreated subterranean coal mine that is eerily dark, cramped, and textured.", "Capacity": "40"},
    {"Name": "Rainbow Beach water filtration plant (Interior)", "Type": "Indoor", "Category": "industrial", "Neighborhood": "South Shore", "Feasibility": 2, "Contact": "", "Booking": "", "IG": "", "Why": "A sprawling mid-century modernist municipal water facility filled with vast, humming machinery rooms.", "Capacity": "Varies"},
    {"Name": "Pullman National Monument (Clock Tower Building)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Pullman", "Feasibility": 7, "Contact": "pull_visitor_info@nps.gov", "Booking": "", "IG": "pullmannationalmonument", "Why": "A radically restored 1880s industrial manufacturing floor featuring pristine brick and massive skylights.", "Capacity": "Varies"},
    {"Name": "Given's Castle", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Beverly", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "", "Why": "An absurd, fully functional 1886 medieval-style limestone castle towering bizarrely over a residential area.", "Capacity": "Varies"},
    {"Name": "John H. Vanderpoel Art Association", "Type": "Indoor", "Category": "gallery", "Neighborhood": "Beverly", "Feasibility": 6, "Contact": "info@vanderpoelartmuseum.org", "Booking": "", "IG": "", "Why": "A strange, densely packed historic gallery of 19th-century oil paintings hidden above a park fieldhouse.", "Capacity": "50"},
    {"Name": "Columbus Park Refectory (Dance hall)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Austin", "Feasibility": 8, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "A beautiful, decaying, wildly romantic Spanish Revival hall with gigantic arched windows looking at water.", "Capacity": "100"},
    {"Name": "Austin Town Hall Park (Indoor Theater)", "Type": "Indoor", "Category": "theater", "Neighborhood": "Austin", "Feasibility": 8, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "A massive, brick neo-Georgian community complex modeled literally after Independence Hall.", "Capacity": "200"},
    {"Name": "Eckhart Park (Indoor fieldhouse)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "West Town", "Feasibility": 8, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "A sprawling prairie-style complex boasting heavy dark woods and a beautifully grim indoor pool room.", "Capacity": "Varies"},
    {"Name": "Cook County Hospital (Restored Lobby / Harrison's)", "Type": "Indoor", "Category": "adaptive reuse", "Neighborhood": "Near West Side", "Feasibility": 7, "Contact": "", "Booking": "", "IG": "", "Why": "Once an iconic decaying ruin, now a terrifyingly massive, meticulously restored Beaux-Arts hall.", "Capacity": "Varies"},
    {"Name": "Simone's", "Type": "Indoor", "Category": "adaptive reuse", "Neighborhood": "Pilsen", "Feasibility": 8, "Contact": "info@simonesbar.com", "Booking": "", "IG": "simonesbar", "Why": "The architectural equivalent of a junkyard fever dream; built entirely from scavenged urban salvage.", "Capacity": "100"},
    {"Name": "Hector Duarte's Studio", "Type": "Indoor", "Category": "studio", "Neighborhood": "Pilsen", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "A private artist studio where the entire massive facade and interior serves as a giant, surreal mural.", "Capacity": "Varies"},
    {"Name": "Art Institute of Chicago (Ryerson and Burnham Libraries)", "Type": "Indoor", "Category": "library", "Neighborhood": "Loop", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "artinstitutechi", "Why": "Hidden deep in the museum, a multi-tiered, strictly silent modernist library under a massive glass roof.", "Capacity": "100"},
    {"Name": "National Veterans Art Museum", "Type": "Indoor", "Category": "museum", "Neighborhood": "Portage Park", "Feasibility": 7, "Contact": "info@nvam.org", "Booking": "", "IG": "nvamuseum", "Why": "An intense juxtaposition of heavy, visceral war art hung against sterile, quiet community gallery walls.", "Capacity": "100"},
    {"Name": "Balzekas Museum of Lithuanian Culture", "Type": "Indoor", "Category": "museum", "Neighborhood": "West Lawn", "Feasibility": 7, "Contact": "info@balzekasmuseum.org", "Booking": "", "IG": "balzekasmuseum", "Why": "Features an impossibly dense, eerie collection of gothic medieval armor and forgotten Eastern European artifacts.", "Capacity": "50"},
    {"Name": "The Insect Asylum", "Type": "Indoor", "Category": "museum", "Neighborhood": "Avondale", "Feasibility": 9, "Contact": "info@theinsectasylum.com", "Booking": "", "IG": "theinsectasylum", "Why": "An incredibly unsettling but beautiful collection of thousands of pinned insects and taxidermy dioramas.", "Capacity": "40"},
    {"Name": "Busy Beaver Button Museum", "Type": "Indoor", "Category": "museum", "Neighborhood": "Logan Square", "Feasibility": 8, "Contact": "info@busybeaver.net", "Booking": "", "IG": "busybeaverbuttonco", "Why": "Thousands of tiny, colorful historical buttons aggressively packed into a wildly vibrant room.", "Capacity": "30"},
    {"Name": "The Rebuilding Exchange", "Type": "Indoor", "Category": "warehouse", "Neighborhood": "Bucktown", "Feasibility": 9, "Contact": "info@rebuildingexchange.org", "Booking": "", "IG": "rxchicago", "Why": "An absolutely sprawling industrial warehouse filled stacked to the ceiling with old salvaged doors and lumber.", "Capacity": "Varies"},
    {"Name": "The WasteShed", "Type": "Indoor", "Category": "warehouse", "Neighborhood": "Humboldt Park", "Feasibility": 9, "Contact": "info@thewasteshed.com", "Booking": "", "IG": "thewasteshed", "Why": "A chaotic, colorful cavern of endless creative reuse materials, fabrics, and eccentric junk.", "Capacity": "30"},
    {"Name": "Guild Row", "Type": "Indoor", "Category": "adaptive reuse", "Neighborhood": "Avondale", "Feasibility": 8, "Contact": "hello@guildrow.co", "Booking": "https://www.guildrow.co", "IG": "guildrow", "Why": "Multi-structure industrial compound heavily focused on raw masonry, woodshops, and massive textiles.", "Capacity": "150"},
    {"Name": "Bridgeport Art Center (Skyline Loft)", "Type": "Indoor", "Category": "loft", "Neighborhood": "Bridgeport", "Feasibility": 10, "Contact": "events@bridgeportart.com", "Booking": "https://bridgeportart.com", "IG": "bridgeportartcenter", "Why": "18,000 square feet of completely open, raw timber loft space floating high above the industrial south side.", "Capacity": "Varies"},
    {"Name": "21c Museum Hotel (Galleries)", "Type": "Indoor", "Category": "gallery", "Neighborhood": "River North", "Feasibility": 8, "Contact": "chicago@21chotels.com", "Booking": "", "IG": "21cchicago", "Why": "Multi-level contemporary art museum wrapped inside an aggressively chic boutique hotel interior.", "Capacity": "Varies"},
    {"Name": "The Martin", "Type": "Indoor", "Category": "gallery", "Neighborhood": "West Town", "Feasibility": 9, "Contact": "themartinchicago@gmail.com", "Booking": "", "IG": "themartinchicago", "Why": "An intensely eclectic, DIY-friendly, wood-heavy artist gallery and storefront brimming with texture.", "Capacity": "50"},
    {"Name": "The Chicago Firehouse Restaurant", "Type": "Indoor", "Category": "adaptive reuse", "Neighborhood": "South Loop", "Feasibility": 8, "Contact": "events@chicagofirehouse.com", "Booking": "", "IG": "chicagofirehouse", "Why": "A literal 1905 firehouse complete with beautifully glazed white brick and an original brass fire pole.", "Capacity": "100"},
    {"Name": "St. Volodymyr and Olha Ukrainian Catholic Church", "Type": "Indoor", "Category": "church", "Neighborhood": "Ukrainian Village", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "Breathtakingly ornate golden and aggressively bright frescoed walls radiating completely unexpected color.", "Capacity": "Varies"},
    {"Name": "St. Nicholas Ukrainian Catholic Cathedral", "Type": "Indoor", "Category": "church", "Neighborhood": "Ukrainian Village", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "Patterned off the St. Sophia in Kyiv, boasting an astonishing 13 domes and deeply saturated interiors.", "Capacity": "Varies"},
    {"Name": "Holy Trinity Polish Catholic Church", "Type": "Indoor", "Category": "church", "Neighborhood": "Noble Square", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "Intensely massive brick gothic church completely lacking columns, leaving an impossibly vast interior.", "Capacity": "Varies"},
    {"Name": "St. Stanislaus Kostka", "Type": "Indoor", "Category": "church", "Neighborhood": "Noble Square", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "Known as the mother church of Polish parishes, dominating the skyline over the expressway with intense spires.", "Capacity": "Varies"},
    {"Name": "St. Alphonsus Church", "Type": "Indoor", "Category": "church", "Neighborhood": "Lakeview", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "stalphonsuschicago", "Why": "An impossibly beautiful blue gothic ceiling adorned with thousands of golden stars arching over stone walls.", "Capacity": "Varies"},
    {"Name": "Monastery of the Holy Cross", "Type": "Indoor", "Category": "church", "Neighborhood": "Bridgeport", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "", "Why": "An active Benedictine monastery featuring a soaring gothic chapel that feels incredibly severe and ancient.", "Capacity": "Varies"},
    {"Name": "Midwest Buddhist Temple", "Type": "Indoor", "Category": "church", "Neighborhood": "Old Town", "Feasibility": 6, "Contact": "info@mbtchicago.org", "Booking": "", "IG": "mbtchicago", "Why": "A stunning, deeply serene mid-century modern Japanese style temple hidden quietly among Victorian homes.", "Capacity": "Varies"},
    {"Name": "The Laramie State Bank (Interior Ruins)", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Austin", "Feasibility": 2, "Contact": "", "Booking": "", "IG": "", "Why": "An absolutely magnificent, rotting Art Deco terra cotta building providing an unbelievable ruin aesthetic.", "Capacity": "Varies"},
    {"Name": "St. Agatha Catholic Church", "Type": "Indoor", "Category": "church", "Neighborhood": "North Lawndale", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "Romanesque architecture featuring huge, imposing double spires and dramatic lighting angles.", "Capacity": "Varies"},
    {"Name": "St. Paul Catholic Church", "Type": "Indoor", "Category": "church", "Neighborhood": "Pilsen", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "A very unusual, deeply wide and heavy brick church specifically built without any towering steeples.", "Capacity": "Varies"},
    {"Name": "The Flatiron Arts Building", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Wicker Park", "Feasibility": 8, "Contact": "", "Booking": "", "IG": "flatironartsbuilding", "Why": "A fiercely chaotic, terrifyingly twisting labyrinth of hallways dripping with decades of artists' paint.", "Capacity": "Varies"},
    # OUTDOOR
    {"Name": "The Kehilath Anshe Ma'ariv Synagogue (Pilgrim Baptist Church Shell)", "Type": "Outdoor", "Category": "historic building", "Neighborhood": "Bronzeville", "Feasibility": 4, "Contact": "", "Booking": "", "IG": "", "Why": "The burned-out, stabilized massive stone exterior walls of a Sullivan and Adler masterpiece standing as a ruin.", "Capacity": "Varies"},
    {"Name": "First Chicago Bank Building (Chase Tower Sunken Plaza)", "Type": "Outdoor", "Category": "public art", "Neighborhood": "Loop", "Feasibility": 8, "Contact": "", "Booking": "", "IG": "", "Why": "A brutalist concrete plaza diving beneath street level, anchored by Marc Chagall's massive colorful mosaic.", "Capacity": "Varies"},
    {"Name": "The Nichols Bridgeway", "Type": "Outdoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 8, "Contact": "", "Booking": "", "IG": "", "Why": "An impossibly long, aggressively modern white blade of a bridge cutting straight into the Art Institute.", "Capacity": "Varies"},
    {"Name": "Vietnam Veterans Memorial (Water Wall)", "Type": "Outdoor", "Category": "public art", "Neighborhood": "Loop", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "A severely stark, massive black granite wall continuously bleeding water into an echoing riverside basin.", "Capacity": "Varies"},
    {"Name": "Riverwalk (The Jetty)", "Type": "Outdoor", "Category": "waterfront", "Neighborhood": "Loop", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "chicagoriverwalk", "Why": "A series of floating concrete piers intensely packed with wild wetland plants right under the massive skyscrapers.", "Capacity": "Varies"},
    {"Name": "Canal Street Railroad Underpasses", "Type": "Outdoor", "Category": "architectural landmark", "Neighborhood": "Fulton Market", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "Relentless grids of colossal, deafeningly loud black steel columns supporting active freight trains above.", "Capacity": "Varies"},
    {"Name": "The Stockyard Gate", "Type": "Outdoor", "Category": "architectural landmark", "Neighborhood": "Back of the Yards", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "A towering, incredibly grim limestone archway standing completely alone in the center of an industrial district.", "Capacity": "Varies"},
    {"Name": "Monument to the Great Northern Migration", "Type": "Outdoor", "Category": "public art", "Neighborhood": "Bronzeville", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "An imposing bronze statue standing fiercely at the entrance of Bronzeville, exuding immense historical gravity.", "Capacity": "Varies"},
    {"Name": "South Side Community Art Center (Exterior courtyard)", "Type": "Outdoor", "Category": "historic building", "Neighborhood": "Bronzeville", "Feasibility": 8, "Contact": "", "Booking": "", "IG": "sscac_chi", "Why": "Classic Georgian revival architecture sharply mixed with dense, textured modernist outdoor art installations.", "Capacity": "Varies"},
    {"Name": "Prairie Avenue Historic District (Cobblestones)", "Type": "Outdoor", "Category": "historic building", "Neighborhood": "South Loop", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "A perfectly preserved strip of authentic cobblestone streets lined exclusively by gigantic Gilded Age mansions.", "Capacity": "Varies"},
    {"Name": "Kenwood historic mansions (Exterior streets)", "Type": "Outdoor", "Category": "historic building", "Neighborhood": "Kenwood", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "Incredibly wide, heavily forested neighborhood streets flanked by sprawling, absurdly vast residential compounds.", "Capacity": "Varies"},
    {"Name": "The Richard J. Daley Center (Plaza)", "Type": "Outdoor", "Category": "public art", "Neighborhood": "Loop", "Feasibility": 8, "Contact": "", "Booking": "", "IG": "", "Why": "A relentlessly barren, windswept granite plaza fiercely guarded by an absolutely massive rusted Picasso sculpture.", "Capacity": "Varies"},
    {"Name": "LaSalle Street Canyon (Ceres Statue view)", "Type": "Outdoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "A deeply shadowy, intensely dark canyon formed by sheer walls of high-finance architecture ending in an Art Deco monolith.", "Capacity": "Varies"},
    {"Name": "57th Street Beach (Underpass with murals)", "Type": "Outdoor", "Category": "public art", "Neighborhood": "Hyde Park", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "A deeply arched, incredibly long stone tunnel extensively coated in vivid, layered community painted scenes.", "Capacity": "Varies"},
    {"Name": "Jackson Park Wooded Island (Nature trails)", "Type": "Outdoor", "Category": "nature preserve", "Neighborhood": "Hyde Park", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "Densely untamed, completely isolated dirt paths that make the city skyline completely magically vanish.", "Capacity": "Varies"},
    {"Name": "The Columbia Basin (Jackson Park)", "Type": "Outdoor", "Category": "waterfront", "Neighborhood": "Hyde Park", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "The sprawling, highly structured reflecting pool remaining directly from the center of the 1893 World's Fair.", "Capacity": "Varies"},
    {"Name": "Calumet Park (Lakefront)", "Type": "Outdoor", "Category": "waterfront", "Neighborhood": "East Side", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "Sweeping views of apocalyptic steel mills contrasting fiercely with pristine, icy Lake Michigan waves.", "Capacity": "Varies"},
    {"Name": "Big Marsh Park (Eco paths)", "Type": "Outdoor", "Category": "nature preserve", "Neighborhood": "South Deering", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "bigmarshchicago", "Why": "A surreal, highly transformed landscape of massive black steel slag paths cutting directly through wild green marshland.", "Capacity": "Varies"},
    {"Name": "Marian R. Byrnes Park", "Type": "Outdoor", "Category": "nature preserve", "Neighborhood": "South Deering", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "A massive, very rarely visited urban wilderness dotted with gigantic man-made hills of rocky industrial waste.", "Capacity": "Varies"},
    {"Name": "The Dan Ryan Woods (The aqueducts)", "Type": "Outdoor", "Category": "park", "Neighborhood": "Beverly", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "Heavy, ancient-looking limestone aqueducts heavily cutting through very dense timber forests on a high ridge.", "Capacity": "Varies"},
    {"Name": "The Ridge Historic District", "Type": "Outdoor", "Category": "historic building", "Neighborhood": "Beverly", "Feasibility": 10, "Contact": "", "Booking": "", "IG": "", "Why": "A profoundly un-Chicago, winding heavily forested, steeply sloping road flanked by massive historic estates.", "Capacity": "Varies"},
    {"Name": "The Western Avenue Overpass (The 606)", "Type": "Outdoor", "Category": "architectural landmark", "Neighborhood": "Bucktown", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "the606chicago", "Why": "An intensely aggressive, wide concrete bridge offering dramatic overpasses crossing over extremely chaotic traffic.", "Capacity": "Varies"},
    {"Name": "The Bloomingdale Trail (Observatory)", "Type": "Outdoor", "Category": "park", "Neighborhood": "Humboldt Park", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "the606chicago", "Why": "A fiercely modern, spiraling grassy hillside expressly built to act as a neighborhood celestial observatory.", "Capacity": "Varies"},
    {"Name": "Wicker Park (The central fountain)", "Type": "Outdoor", "Category": "park", "Neighborhood": "Wicker Park", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "wickerparkchicago", "Why": "A heavily ornate historic cast-iron fountain surrounded entirely by fiercely angular Victorian mansions.", "Capacity": "Varies"},
    {"Name": "The Robey (The Cabana Club rooftop)", "Type": "Outdoor", "Category": "rooftop", "Neighborhood": "Wicker Park", "Feasibility": 8, "Contact": "events@therobey.com", "Booking": "therobey.com", "IG": "therobeychicago", "Why": "An impossibly distinct triangular pool deck completely dominating the chaotic intersection of three major avenues.", "Capacity": "Varies"},
    {"Name": "Lincoln Park Zoo (Honeycomb pavilion)", "Type": "Outdoor", "Category": "architectural landmark", "Neighborhood": "Lincoln Park", "Feasibility": 8, "Contact": "events@lpzoo.org", "Booking": "", "IG": "lincolnparkzoo", "Why": "Studio Gang designed incredibly swooping, massive wooden honeycomb pod framing the water and skyscrapers.", "Capacity": "Varies"},
    {"Name": "Oak Street Beach (Pedestrian tunnel)", "Type": "Outdoor", "Category": "public art", "Neighborhood": "Gold Coast", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "An incredibly long, deeply shadowy concrete tube fiercely leading the roaring city straight onto the bright beach.", "Capacity": "Varies"},
    {"Name": "The Lakefront Trail (Chess Pavilion)", "Type": "Outdoor", "Category": "architectural landmark", "Neighborhood": "Lincoln Park", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "An extremely brutalist exposed concrete cantilever jutting confidently right out over the crashing lake water.", "Capacity": "Varies"},
    {"Name": "Montrose Harbor (The docks)", "Type": "Outdoor", "Category": "waterfront", "Neighborhood": "Uptown", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "A sprawling, jagged maze of metallic boating slips staring directly down the massive skyline profile.", "Capacity": "Varies"},
    {"Name": "Alta Vista Terrace", "Type": "Outdoor", "Category": "historic building", "Neighborhood": "Wrigleyville", "Feasibility": 10, "Contact": "", "Booking": "", "IG": "", "Why": "A terrifyingly perfect, extremely narrow street of exact replica London rowhouses completely out of place in space.", "Capacity": "Varies"}
]


def load_memory():
    memory = set()
    if os.path.exists(MEMORY_FILE):
        with open(MEMORY_FILE, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                memory.add(row['Location Name'].lower().strip())
    return memory

def write_memory(new_locations):
    file_exists = os.path.exists(MEMORY_FILE)
    with open(MEMORY_FILE, 'a', encoding='utf-8', newline='') as f:
        fieldnames = ['Location Name', 'Type', 'Space Category', 'Neighborhood', 'Feasibility Score', 'Contact Info', 'Booking Link', 'IG/Social Link', 'Why It\'s Interesting', 'Capacity Estimate']
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        if not file_exists:
            writer.writeheader()
        for loc in new_locations:
            writer.writerow(loc)

def main():
    memory = load_memory()
    
    unique_locations = []
    
    for loc in locations:
        loc_name = loc['Name'].lower().strip()
        if loc_name not in memory:
            row = {
                'Location Name': loc['Name'],
                'Type': loc['Type'],
                'Space Category': loc['Category'],
                'Neighborhood': loc['Neighborhood'],
                'Feasibility Score': loc['Feasibility'],
                'Contact Info': loc['Contact'],
                'Booking Link': loc['Booking'],
                'IG/Social Link': loc['IG'],
                'Why It\'s Interesting': loc['Why'],
                'Capacity Estimate': loc['Capacity']
            }
            unique_locations.append(row)
            
    print(f"Sourced {len(unique_locations)} unique locations.")
    print(f"Number of duplicates rejected: {len(locations) - len(unique_locations)}")
    
    with open(OUTPUT_FILE, 'w', encoding='utf-8', newline='') as f:
        fieldnames = ['Location Name', 'Type', 'Space Category', 'Neighborhood', 'Feasibility Score', 'Contact Info', 'Booking Link', 'IG/Social Link', 'Why It\'s Interesting', 'Capacity Estimate']
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(unique_locations)
        
    print(f"Run data written to {OUTPUT_FILE}")
    
    write_memory(unique_locations)
    print("Memory updated successfully.")

if __name__ == '__main__':
    main()
