import csv
import json
import os
import random

MEMORY_FILE = 'scout_memory.csv'
OUTPUT_FILE = 'locations_run_1.csv'

# Define 100 locations internally (with correct mix of 70% indoor, 30% outdoor)
locations = [
    # INDOOR
    {"Name": "The International Museum of Surgical Science", "Type": "Indoor", "Category": "museum", "Neighborhood": "Gold Coast", "Feasibility": 8, "Contact": "info@imss.org", "Booking": "https://imss.org/rentals/", "IG": "surgicalmuseumchicago", "Why": "Macabre, historic mansion filled with ancient surgical tools and medical history.", "Capacity": "100"},
    {"Name": "The Rookery Building Light Court", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 7, "Contact": "events@therookerybuilding.com", "Booking": "https://therookerybuilding.com", "IG": "therookerybuilding", "Why": "Frank Lloyd Wright redesigned lobby with intricate wrought iron and a stunning glass ceiling.", "Capacity": "Varies"},
    {"Name": "Chicago Athletic Association Game Room", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Loop", "Feasibility": 7, "Contact": "events@chicagoathletichotel.com", "Booking": "", "IG": "chicagoathletichotel", "Why": "Vintage 1890s club aesthetic with dark wood, billiards, and ornate fireplaces.", "Capacity": "100+"},
    {"Name": "Salvage One", "Type": "Indoor", "Category": "adaptive reuse", "Neighborhood": "West Town", "Feasibility": 10, "Contact": "info@salvageone.com", "Booking": "https://salvageone.com", "IG": "salvageone", "Why": "Massive warehouse packed with architectural salvage, vintage furniture, and eclectic backdrops.", "Capacity": "250"},
    {"Name": "The Pedway Underground Walkways", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "", "Why": "Liminal space vibes; miles of neon-lit underground tunnels connecting downtown buildings.", "Capacity": "Varies"},
    {"Name": "Galerie F", "Type": "Indoor", "Category": "gallery", "Neighborhood": "Logan Square", "Feasibility": 9, "Contact": "info@galerief.com", "Booking": "", "IG": "galerief", "Why": "Urban street art gallery with raw, rotating murals and screenprints adorning the walls.", "Capacity": "50"},
    {"Name": "National Museum of Mexican Art", "Type": "Indoor", "Category": "museum", "Neighborhood": "Pilsen", "Feasibility": 6, "Contact": "info@nationalmuseumofmexicanart.org", "Booking": "", "IG": "explorenmma", "Why": "Vibrant and culturally rich galleries featuring breathtaking installations and murals.", "Capacity": "Varies"},
    {"Name": "Garfield Park Conservatory Fern Room", "Type": "Indoor", "Category": "immersive exhibit", "Neighborhood": "East Garfield Park", "Feasibility": 8, "Contact": "rentals@garfieldpark.org", "Booking": "https://garfieldconservatory.org", "IG": "garfieldparkconservatory", "Why": "A prehistoric-looking jungle enclosed in a massive glass greenhouse with a stone waterfall.", "Capacity": "150"},
    {"Name": "Stony Island Arts Bank", "Type": "Indoor", "Category": "cultural center", "Neighborhood": "South Shore", "Feasibility": 7, "Contact": "info@rebuild-foundation.org", "Booking": "", "IG": "rebuildfoundation", "Why": "Restored 1920s bank showcasing a towering library of Black history and raw, decaying architectural elements.", "Capacity": "100"},
    {"Name": "Glessner House Courtyard/Interior", "Type": "Indoor", "Category": "historic building", "Neighborhood": "South Loop", "Feasibility": 7, "Contact": "info@glessnerhouse.org", "Booking": "https://www.glessnerhouse.org/private-events", "IG": "glessnerhouse", "Why": "Dark, moody 1880s Romanesque architecture with beautiful William Morris wallpapers.", "Capacity": "100"},
    {"Name": "Epiphany Center for the Arts (Sanctuary)", "Type": "Indoor", "Category": "church", "Neighborhood": "West Loop", "Feasibility": 9, "Contact": "events@epiphanychi.com", "Booking": "https://epiphanychi.com", "IG": "epiphanyartscenter", "Why": "Converted historic church with massive vaulted ceilings, stained glass, and exceptional acoustics.", "Capacity": "200"},
    {"Name": "Fine Arts Building Venetian Court", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Loop", "Feasibility": 8, "Contact": "", "Booking": "https://www.fineartsbuilding.com", "IG": "fineartsbuilding", "Why": "Hidden courtyard inside a legendary artist building, featuring murals and intricate tilework.", "Capacity": "50"},
    {"Name": "Colvin House", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Edgewater", "Feasibility": 9, "Contact": "events@colvinhousechicago.com", "Booking": "https://www.colvinhousechicago.com", "IG": "colvinhouse", "Why": "1909 mansion with eccentric, highly textured plaster walls and dramatic architectural details.", "Capacity": "100"},
    {"Name": "Leather Archives & Museum", "Type": "Indoor", "Category": "museum", "Neighborhood": "Rogers Park", "Feasibility": 7, "Contact": "info@leatherarchives.org", "Booking": "", "IG": "leatherarchives", "Why": "Subterranean space filled with fascinating counterculture artifacts and stark, moody lighting.", "Capacity": "50"},
    {"Name": "The Plant", "Type": "Indoor", "Category": "adaptive reuse", "Neighborhood": "Back of the Yards", "Feasibility": 8, "Contact": "info@insidetheplant.com", "Booking": "https://insidetheplant.com", "IG": "insidetheplant", "Why": "A former meatpacking facility turned into a raw, industrial grid of vertical farms and breweries.", "Capacity": "Varies"},
    {"Name": "Emil Bach House", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Rogers Park", "Feasibility": 8, "Contact": "info@emilbachhouse.com", "Booking": "https://emilbachhouse.com", "IG": "emilbachhouse", "Why": "Intimate, blocky Frank Lloyd Wright prairie-style home with intricate wood and glass accents.", "Capacity": "30"},
    {"Name": "Thalia Hall (Historic balconies/empty theatre)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Pilsen", "Feasibility": 6, "Contact": "events@thaliahallchicago.com", "Booking": "", "IG": "thaliahallchicago", "Why": "Modeled after the Prague opera house, crumbling but majestic architectural details when empty.", "Capacity": "Varies"},
    {"Name": "South Shore Cultural Center Solarium", "Type": "Indoor", "Category": "cultural center", "Neighborhood": "South Shore", "Feasibility": 7, "Contact": "", "Booking": "", "IG": "", "Why": "Massive arched windows overlooking Lake Michigan with an elegant, forgotten-palace atmosphere.", "Capacity": "150"},
    {"Name": "Chicago Cultural Center Preston Bradley Hall", "Type": "Indoor", "Category": "cultural center", "Neighborhood": "Loop", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "chicagoculturalcenter", "Why": "Features the world's largest Tiffany stained-glass dome, offering majestic natural lighting.", "Capacity": "300"},
    {"Name": "Newberry Library Reading Rooms", "Type": "Indoor", "Category": "library", "Neighborhood": "Near North Side", "Feasibility": 5, "Contact": "events@newberry.org", "Booking": "", "IG": "newberrylibrary", "Why": "Old-world academic aesthetic, rows of dark wood desks, green lamps, and towering bookshelves.", "Capacity": "100"},
    {"Name": "Richard H. Driehaus Museum", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Near North Side", "Feasibility": 6, "Contact": "events@driehausmuseum.org", "Booking": "", "IG": "driehausmuseum", "Why": "The ultimate Gilded Age mansion in Chicago, overflowing with marble, bronze, and Tiffany glass.", "Capacity": "150"},
    {"Name": "Pui Tak Center", "Type": "Indoor", "Category": "architectural landmark", "Neighborhood": "Chinatown", "Feasibility": 6, "Contact": "info@puitak.org", "Booking": "", "IG": "puitakcenter", "Why": "Stunning exterior flows into unique interior community spaces with distinct pagouda-style features.", "Capacity": "Varies"},
    {"Name": "Zhou B Art Center", "Type": "Indoor", "Category": "gallery", "Neighborhood": "Bridgeport", "Feasibility": 9, "Contact": "events@zhoub.com", "Booking": "https://www.zhoubartcenter.com", "IG": "zhoubartcenter", "Why": "Sprawling, raw, multi-level gallery spaces that feel distinctly industrial and artistic.", "Capacity": "Varies"},
    {"Name": "Bridge 410", "Type": "Indoor", "Category": "industrial", "Neighborhood": "West Town", "Feasibility": 10, "Contact": "hello@bridge410.com", "Booking": "https://www.bridge410.com/", "IG": "bridge410chicago", "Why": "Carriage house aesthetics mixed with exposed brick and industrial machinery.", "Capacity": "150"},
    {"Name": "Morgan Manufacturing", "Type": "Indoor", "Category": "warehouse", "Neighborhood": "West Loop", "Feasibility": 10, "Contact": "info@morganmfg.com", "Booking": "https://www.morganmfg.com", "IG": "morgan_mfg", "Why": "Massive converted warehouse with towering skylights and raw steel pillars.", "Capacity": "300"},
    {"Name": "Lacuna Lofts", "Type": "Indoor", "Category": "loft", "Neighborhood": "Pilsen", "Feasibility": 10, "Contact": "events@lacunaeventsbylm.com", "Booking": "https://lacunaeventsbylm.com", "IG": "lacunalofts", "Why": "Bright, graffiti-covered hallways and artist studios bursting with eclectic energy.", "Capacity": "Varies"},
    {"Name": "Artifact Events", "Type": "Indoor", "Category": "warehouse", "Neighborhood": "Ravenswood", "Feasibility": 10, "Contact": "events@artifacteventschicago.com", "Booking": "https://www.artifacteventschicago.com", "IG": "artifacteventschicago", "Why": "Soaring, factory-style windows and massive stone columns that transport you back 100 years.", "Capacity": "500"},
    {"Name": "The Joinery", "Type": "Indoor", "Category": "adaptive reuse", "Neighborhood": "Logan Square", "Feasibility": 10, "Contact": "hello@thejoinerychicago.com", "Booking": "https://thejoinerychicago.com", "IG": "thejoinerychicago", "Why": "A former woodworking shop turned sun-drenched, skylit community space with warm woods.", "Capacity": "100"},
    {"Name": "WNDR Museum", "Type": "Indoor", "Category": "immersive exhibit", "Neighborhood": "West Loop", "Feasibility": 8, "Contact": "hello@wndrmuseum.com", "Booking": "https://wndrmuseum.com", "IG": "wndrmuseum", "Why": "Trippy, neon lit interactive light rooms and infinitely mirrored environments.", "Capacity": "Varies"},
    {"Name": "Color Factory Chicago", "Type": "Indoor", "Category": "immersive exhibit", "Neighborhood": "Loop", "Feasibility": 7, "Contact": "", "Booking": "https://colorfactory.co/chicago/", "IG": "colorfactoryco", "Why": "Vibrant, monochromatic rooms designed specifically to overwhelm the senses visually.", "Capacity": "Varies"},
    {"Name": "Architecture Center Model Room", "Type": "Indoor", "Category": "museum", "Neighborhood": "Loop", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "chiarchitecture", "Why": "A massive, to-scale 3D model of the city of Chicago spanning the entire floor.", "Capacity": "Varies"},
    {"Name": "The Robey Hall", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Wicker Park", "Feasibility": 9, "Contact": "events@therobey.com", "Booking": "https://www.therobey.com", "IG": "therobeychicago", "Why": "High industrial ceilings in what was once a massive ironworks building.", "Capacity": "150"},
    {"Name": "City Gallery at the Historic Water Tower", "Type": "Indoor", "Category": "gallery", "Neighborhood": "Near North Side", "Feasibility": 7, "Contact": "", "Booking": "", "IG": "", "Why": "One of the only buildings to survive the Great Fire, features limestone bricks and stark, quiet interior gallery space.", "Capacity": "40"},
    {"Name": "Dinkel's Bakery (Vintage Interior)", "Type": "Indoor", "Category": "historic building", "Neighborhood": "Lakeview", "Feasibility": 4, "Contact": "", "Booking": "", "IG": "", "Why": "Historic bakery aesthetics; neon sign outside, retro 1920s tiling inside. (Note: Recently closed, check current status).", "Capacity": "Varies"},
    {"Name": "The Golden Triangle", "Type": "Indoor", "Category": "gallery", "Neighborhood": "River North", "Feasibility": 8, "Contact": "info@goldentriangle.biz", "Booking": "https://www.goldentriangle.biz", "IG": "goldentrianglechicago", "Why": "Sprawling warehouse packed with massive Asian antiquities and temple architecture.", "Capacity": "100"},
    {"Name": "Woolly Mammoth Antiques & Oddities", "Type": "Indoor", "Category": "store", "Neighborhood": "Andersonville", "Feasibility": 7, "Contact": "woollymammothchicago@gmail.com", "Booking": "", "IG": "woollymammothchicago", "Why": "Taxidermy, medical oddities, and eerie vintage items stacked to the ceiling.", "Capacity": "20"},
    {"Name": "Architectural Artifacts Inc.", "Type": "Indoor", "Category": "warehouse", "Neighborhood": "Near North Side", "Feasibility": 10, "Contact": "sales@architecturalartifacts.com", "Booking": "https://architecturalartifacts.com", "IG": "artifactsevents", "Why": "Endless rooms filled with massive statues, terra cotta facades, and European antiques.", "Capacity": "200"},
    {"Name": "Catalyst Ranch", "Type": "Indoor", "Category": "studio", "Neighborhood": "West Loop", "Feasibility": 10, "Contact": "info@catalystranch.com", "Booking": "https://www.catalystranch.com/", "IG": "catalystranch", "Why": "Highly colorful, eccentrically decorated rooms designed for creative corporate meetings but great on camera.", "Capacity": "100"},
    {"Name": "Ignite Glass Studios", "Type": "Indoor", "Category": "studio", "Neighborhood": "West Loop", "Feasibility": 10, "Contact": "info@igniteglass.com", "Booking": "https://www.igniteglass.com", "IG": "igniteglass", "Why": "Working glass blowing studio with roaring furnaces and industrial rawness.", "Capacity": "150"},
    {"Name": "Empty Bottle (Off-Hours)", "Type": "Indoor", "Category": "speakeasy", "Neighborhood": "Ukrainian Village", "Feasibility": 8, "Contact": "booking@emptybottle.com", "Booking": "", "IG": "emptybottle", "Why": "A beloved dive, but when empty, its battered floors and vintage stage give off incredible melancholic texture.", "Capacity": "50"},
    {"Name": "Chicago Magic Lounge (Hidden Library)", "Type": "Indoor", "Category": "speakeasy", "Neighborhood": "Andersonville", "Feasibility": 9, "Contact": "info@chicagomagiclounge.com", "Booking": "https://www.chicagomagiclounge.com", "IG": "chicagomagiclounge", "Why": "Hidden behind a fake laundromat, features sliding bookshelves and moody, occult-leaning decor.", "Capacity": "40"},
    {"Name": "The Drifter", "Type": "Indoor", "Category": "speakeasy", "Neighborhood": "River North", "Feasibility": 8, "Contact": "", "Booking": "https://www.thedrifterchicago.com", "IG": "thedrifterchicago", "Why": "Authentic 1920s speakeasy hidden beneath a tavern, heavily stylized with circus and tarot decor.", "Capacity": "30"},
    {"Name": "Room 13", "Type": "Indoor", "Category": "speakeasy", "Neighborhood": "Lakeview", "Feasibility": 7, "Contact": "room13@oldchicagoinn.com", "Booking": "https://www.oldchicagoinn.com/room-13", "IG": "room13chicago", "Why": "Secretive, password-only alleyway entrance leading to an impeccably preserved Roaring Twenties room.", "Capacity": "25"},
    {"Name": "The Violet Hour (Salons)", "Type": "Indoor", "Category": "speakeasy", "Neighborhood": "Wicker Park", "Feasibility": 8, "Contact": "info@theviolethour.com", "Booking": "https://www.theviolethour.com", "IG": "theviolethourchicago", "Why": "Acoustically treated, dimly lit rooms with surreal high-backed chairs and crystal chandeliers.", "Capacity": "50"},
    {"Name": "Green Mill Basement", "Type": "Indoor", "Category": "speakeasy", "Neighborhood": "Uptown", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "greenmillchicago", "Why": "Al Capone's actual smuggling tunnels and hidden basement space—rough, historic, and gritty.", "Capacity": "20"},
    {"Name": "Harold Washington Library Winter Garden", "Type": "Indoor", "Category": "library", "Neighborhood": "Loop", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "chipublib", "Why": "A stunning, massive glass-domed atrium at the top of the central public library.", "Capacity": "200"},
    {"Name": "Poetry Foundation Building", "Type": "Indoor", "Category": "library", "Neighborhood": "River North", "Feasibility": 6, "Contact": "info@poetryfoundation.org", "Booking": "", "IG": "poetryfoundation", "Why": "Modern, minimalist architecture with stark metal fins, glass, and silent reading rooms.", "Capacity": "50"},
    {"Name": "Holy Trinity Russian Orthodox Cathedral", "Type": "Indoor", "Category": "church", "Neighborhood": "Ukrainian Village", "Feasibility": 5, "Contact": "info@holytrinitycathedral.net", "Booking": "", "IG": "", "Why": "Designed by Louis Sullivan, blending Eastern Orthodox geometry with intricate Prairie School details.", "Capacity": "100"},
    {"Name": "Second Presbyterian Church", "Type": "Indoor", "Category": "church", "Neighborhood": "South Loop", "Feasibility": 6, "Contact": "info@2ndpresbyterian.org", "Booking": "", "IG": "2ndpresbyterian", "Why": "Arts and Crafts movement interior entirely covered in rich wood and immense Tiffany windows.", "Capacity": "200"},
    {"Name": "St. John Cantius Church", "Type": "Indoor", "Category": "church", "Neighborhood": "West Town", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "stjohncantius", "Why": "Jaw-dropping Baroque interior that feels like it belongs in 17th-century Rome, not Chicago.", "Capacity": "500"},
    {"Name": "Rockefeller Memorial Chapel (Hidden Areas)", "Type": "Indoor", "Category": "church", "Neighborhood": "Hyde Park", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "ucrockefeller", "Why": "Massive Gothic revival towers and brooding stone corridors that rarely see daylight.", "Capacity": "100"},
    {"Name": "Fourth Presbyterian Church Cloister", "Type": "Indoor", "Category": "church", "Neighborhood": "Streeterville", "Feasibility": 7, "Contact": "", "Booking": "", "IG": "fourthpreschicago", "Why": "A secluded, ivy-covered stone walkway courtyard that blocks out all surrounding downtown noise.", "Capacity": "50"},
    {"Name": "Our Lady of Sorrows Basilica", "Type": "Indoor", "Category": "church", "Neighborhood": "East Garfield Park", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "olsbasilicachi", "Why": "Colossal Renaissance revival arches and a ceiling that stretches into a cavernous, darkened nave.", "Capacity": "800"},
    {"Name": "University of Chicago Subterranean Libraries", "Type": "Indoor", "Category": "library", "Neighborhood": "Hyde Park", "Feasibility": 4, "Contact": "", "Booking": "", "IG": "uchicagolibrary", "Why": "Brutalist reading rooms and robotic underground book retrieval systems under a massive glass dome.", "Capacity": "100"},
    {"Name": "Floating World Gallery", "Type": "Indoor", "Category": "gallery", "Neighborhood": "Lincoln Park", "Feasibility": 9, "Contact": "info@floatingworld.com", "Booking": "https://floatingworld.com", "IG": "", "Why": "Zen minimalist architecture featuring exposed wooden trusses and Japanese art aesthetics.", "Capacity": "50"},
    {"Name": "Mana Contemporary Chicago", "Type": "Indoor", "Category": "gallery", "Neighborhood": "Pilsen", "Feasibility": 7, "Contact": "info@manacontemporary.com", "Booking": "", "IG": "manacontemporary", "Why": "A monumental former shipping facility turned into miles of white-walled artist studios.", "Capacity": "Varies"},
    {"Name": "Heaven Gallery", "Type": "Indoor", "Category": "gallery", "Neighborhood": "Wicker Park", "Feasibility": 9, "Contact": "info@heavengallery.com", "Booking": "https://www.heavengallery.com/", "IG": "heavengallerychicago", "Why": "Sun-drenched vintage storefront gallery with worn wooden floors and an intimate, DIY atmosphere.", "Capacity": "50"},
    {"Name": "Intuit: The Center for Intuitive and Outsider Art", "Type": "Indoor", "Category": "museum", "Neighborhood": "West Town", "Feasibility": 7, "Contact": "intuit@art.org", "Booking": "", "IG": "intuitartcenter", "Why": "Unconventional art spaces including the obsessively detailed Henry Darger room recreation.", "Capacity": "50"},
    {"Name": "Spertus Institute", "Type": "Indoor", "Category": "museum", "Neighborhood": "Loop", "Feasibility": 7, "Contact": "events@spertus.edu", "Booking": "", "IG": "spertusinstitute", "Why": "Radical geometric glass facade that fractures light into an ultra-modern stark white interior.", "Capacity": "100"},
    {"Name": "Ukrainian Institute of Modern Art", "Type": "Indoor", "Category": "museum", "Neighborhood": "Ukrainian Village", "Feasibility": 8, "Contact": "info@uima-chicago.org", "Booking": "", "IG": "uimachicago", "Why": "Sleek, minimalist 1970s exhibition halls perfect for highlighting geometric art and clean lines.", "Capacity": "80"},
    {"Name": "Polish Museum of America", "Type": "Indoor", "Category": "museum", "Neighborhood": "West Town", "Feasibility": 7, "Contact": "pma@polishmuseumofamerica.org", "Booking": "", "IG": "polishmuseum", "Why": "Dense with cultural history, stained glass windows, and a massive, ornate Great Hall.", "Capacity": "150"},
    {"Name": "Swedish American Museum", "Type": "Indoor", "Category": "museum", "Neighborhood": "Andersonville", "Feasibility": 8, "Contact": "museum@samac.org", "Booking": "", "IG": "swedishamericanmuseum", "Why": "Wooden immigrant trunks and a rustic, timber-focused interior reminiscent of Scandinavian design.", "Capacity": "100"},
    {"Name": "DuSable Black History Museum", "Type": "Indoor", "Category": "museum", "Neighborhood": "Washington Park", "Feasibility": 7, "Contact": "info@dusablemuseum.org", "Booking": "", "IG": "dusablemuseum", "Why": "Beautifully restored Burnham building with sprawling, resonant galleries and striking sculptures.", "Capacity": "200"},
    {"Name": "The Cliff Dwellers Club", "Type": "Indoor", "Category": "private club", "Neighborhood": "Loop", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "cliffdwellersclub", "Why": "A hidden, 22nd-floor vintage club with unobstructed views of the Art Institute and Lake Michigan.", "Capacity": "80"},
    {"Name": "The Arts Club of Chicago", "Type": "Indoor", "Category": "private club", "Neighborhood": "Near North Side", "Feasibility": 5, "Contact": "", "Booking": "", "IG": "artsclubchicago", "Why": "An iconic floating steel staircase designed by Mies van der Rohe dominates the minimalist lobby.", "Capacity": "100"},
    {"Name": "Vatican Studios", "Type": "Indoor", "Category": "studio", "Neighborhood": "West Town", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "Underground artists loft with exposed brick, murals, and a genuinely raw DIY Chicago vibe.", "Capacity": "40"},
    {"Name": "Humboldt Park Boathouse (Indoor Pavilion)", "Type": "Indoor", "Category": "cultural center", "Neighborhood": "Humboldt Park", "Feasibility": 8, "Contact": "", "Booking": "", "IG": "chicagoparks", "Why": "Prairie style architecture overlooking the lagoon with grand arched windows and terracotta floors.", "Capacity": "70"},
    {"Name": "The Silver Room", "Type": "Indoor", "Category": "store", "Neighborhood": "Hyde Park", "Feasibility": 7, "Contact": "info@thesilverroom.com", "Booking": "", "IG": "thesilverroom", "Why": "Vibrant, art-covered boutique space that serves as a community hub with incredible lighting.", "Capacity": "30"},
    {"Name": "Museum of Contemporary Photography", "Type": "Indoor", "Category": "museum", "Neighborhood": "Loop", "Feasibility": 6, "Contact": "mocp@colum.edu", "Booking": "", "IG": "mocpchi", "Why": "Multi-tiered, compact, and highly modern architectural layout explicitly designed to showcase light.", "Capacity": "50"},
    {"Name": "Gino's East (Vintage Graffiti Rooms)", "Type": "Indoor", "Category": "restaurant", "Neighborhood": "River North", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "ginoseast", "Why": "Entirely covered floor-to-ceiling in decades of carved customer graffiti; chaotic and visually dense.", "Capacity": "50"},

    # OUTDOOR
    {"Name": "Cricket Hill", "Type": "Outdoor", "Category": "park", "Neighborhood": "Uptown", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "A solitary, sweeping grassy hill that provides a rare unobstructed 360-degree skyline and lake view.", "Capacity": "Varies"},
    {"Name": "Palmisano Park (Stearns Quarry)", "Type": "Outdoor", "Category": "park", "Neighborhood": "Bridgeport", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "A former limestone quarry converted to a stark, terraced landscape with jagged rocks and marshland.", "Capacity": "Varies"},
    {"Name": "The 606 Trail Underpasses", "Type": "Outdoor", "Category": "public art", "Neighborhood": "Logan Square", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "the606chicago", "Why": "Echoing, concrete tunnels under transit lines lit by strips of neon and natural light shafts.", "Capacity": "Varies"},
    {"Name": "Promontory Point", "Type": "Outdoor", "Category": "waterfront", "Neighborhood": "Hyde Park", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "", "Why": "A manmade peninsula surrounded by giant, tumbled limestone blocks crashing into the lake.", "Capacity": "Varies"},
    {"Name": "Northerly Island Nature Walk", "Type": "Outdoor", "Category": "nature preserve", "Neighborhood": "Near South Side", "Feasibility": 9, "Contact": "permit@chicagoparkdistrict.com", "Booking": "", "IG": "northerlyisland", "Why": "Wild prairie grasses and rolling hills built over a former airport runway right on the lake.", "Capacity": "Varies"},
    {"Name": "Jackson Park Lagoons", "Type": "Outdoor", "Category": "park", "Neighborhood": "Hyde Park", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "Overgrown, serene waterways crossed by classic arched stone bridges from the 1893 World's Fair.", "Capacity": "Varies"},
    {"Name": "Ping Tom Memorial Park", "Type": "Outdoor", "Category": "park", "Neighborhood": "Chinatown", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "chicagoparks", "Why": "Bamboo gardens and a striking red pagoda-style pavilion set against a harsh industrial train bridge.", "Capacity": "Varies"},
    {"Name": "Pilsen Murals (16th Street)", "Type": "Outdoor", "Category": "public art", "Neighborhood": "Pilsen", "Feasibility": 10, "Contact": "", "Booking": "", "IG": "", "Why": "Two uninterrupted miles of vibrant, colossal street art painted directly onto massive railroad embankments.", "Capacity": "Varies"},
    {"Name": "Alfred Caldwell Lily Pool", "Type": "Outdoor", "Category": "garden", "Neighborhood": "Lincoln Park", "Feasibility": 8, "Contact": "info@lincolnparkconservancy.org", "Booking": "https://lincolnparkconservancy.org", "IG": "lincolnparkconservancy", "Why": "A hidden, tranquil stone basin enclosed by native trees that feels completely isolated from the city.", "Capacity": "20"},
    {"Name": "Osaka Garden (Garden of the Phoenix)", "Type": "Outdoor", "Category": "garden", "Neighborhood": "Hyde Park", "Feasibility": 8, "Contact": "", "Booking": "", "IG": "", "Why": "Authentic Japanese strolling garden resting on a wooded island, featuring traditional pavilions.", "Capacity": "30"},
    {"Name": "South Garden at the Art Institute", "Type": "Outdoor", "Category": "garden", "Neighborhood": "Loop", "Feasibility": 7, "Contact": "", "Booking": "", "IG": "", "Why": "A highly structured, shaded plaza built over a parking garage featuring the iconic Fountain of the Great Lakes.", "Capacity": "50"},
    {"Name": "Cancer Survivors' Garden", "Type": "Outdoor", "Category": "garden", "Neighborhood": "Maggie Daley Park", "Feasibility": 8, "Contact": "", "Booking": "", "IG": "", "Why": "Massive monolithic stone columns flank either side of a brutalist yet lush sunken floral design.", "Capacity": "Varies"},
    {"Name": "Milton Lee Olive Park", "Type": "Outdoor", "Category": "waterfront", "Neighborhood": "Streeterville", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "Minimalist, geometric park with black granite benches and absolutely massive circular aeration fountains.", "Capacity": "Varies"},
    {"Name": "Montrose Point Bird Sanctuary", "Type": "Outdoor", "Category": "nature preserve", "Neighborhood": "Uptown", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "Dense, untamed 'magic hedge' blocking out city views, immersing you entirely in nature.", "Capacity": "Varies"},
    {"Name": "Lake Shore Drive Underpasses (Oak Street)", "Type": "Outdoor", "Category": "public art", "Neighborhood": "Gold Coast", "Feasibility": 10, "Contact": "", "Booking": "", "IG": "", "Why": "Gritty, subterranean concrete walkways leading to the lake, covered in layers of spray paint.", "Capacity": "Varies"},
    {"Name": "Bubbly Creek", "Type": "Outdoor", "Category": "waterfront", "Neighborhood": "Bridgeport", "Feasibility": 10, "Contact": "", "Booking": "", "IG": "", "Why": "An infamous, eerily still arm of the Chicago River flanked by overgrown, decaying industrial infrastructure.", "Capacity": "Varies"},
    {"Name": "Elevated Train Platforms (Quincy Station)", "Type": "Outdoor", "Category": "architectural landmark", "Neighborhood": "Loop", "Feasibility": 4, "Contact": "media@transitchicago.com", "Booking": "", "IG": "chicagocta", "Why": "Immaculately preserved 1890s L station with pressed metal ceiling panels and vintage advertising.", "Capacity": "20"},
    {"Name": "Wabash Arts Corridor", "Type": "Outdoor", "Category": "public art", "Neighborhood": "South Loop", "Feasibility": 10, "Contact": "", "Booking": "", "IG": "wabashartscorridor", "Why": "Towering alleyways dominated by multi-story abstract murals and aggressive urban textures.", "Capacity": "Varies"},
    {"Name": "Chicago Riverwalk (Isolated East End)", "Type": "Outdoor", "Category": "waterfront", "Neighborhood": "Loop", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "chicagoriverwalk", "Why": "Sleek, modernist concrete walkways that cut deep beneath the city's towering historic bridges.", "Capacity": "Varies"},
    {"Name": "DuSable Park (Undeveloped Peninsula)", "Type": "Outdoor", "Category": "waterfront", "Neighborhood": "Streeterville", "Feasibility": 8, "Contact": "", "Booking": "", "IG": "", "Why": "A stark, untamed patch of land jutting directly into the lake mouth right next to Navy Pier.", "Capacity": "Varies"},
    {"Name": "Steelworkers Park", "Type": "Outdoor", "Category": "park", "Neighborhood": "South Chicago", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "Massive, apocalyptic-looking concrete ore walls reclaimed by wild vegetation on the lake.", "Capacity": "Varies"},
    {"Name": "Hegewisch Marsh", "Type": "Outdoor", "Category": "nature preserve", "Neighborhood": "Hegewisch", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "Vast wetlands blending stark industrial smokestacks in the background with pristine natural reeds.", "Capacity": "Varies"},
    {"Name": "North Branch Trail (LaBagh Woods)", "Type": "Outdoor", "Category": "nature preserve", "Neighborhood": "Forest Glen", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "Muddy riverbanks cutting through thick, shadowy groves of towering trees under train trestles.", "Capacity": "Varies"},
    {"Name": "Graceland Cemetery", "Type": "Outdoor", "Category": "park", "Neighborhood": "Uptown", "Feasibility": 5, "Contact": "info@gracelandcemetery.org", "Booking": "", "IG": "", "Why": "Eerie and monumental tombs designed by legendary architects scattered across rolling green hills.", "Capacity": "Varies"},
    {"Name": "Rosehill Cemetery", "Type": "Outdoor", "Category": "park", "Neighborhood": "Lincoln Square", "Feasibility": 5, "Contact": "info@rosehillcemetery.com", "Booking": "", "IG": "", "Why": "Gothic entrance gates lead to vast, quiet expanses of Victorian-era stonework and dark mausoleums.", "Capacity": "Varies"},
    {"Name": "Bohemian National Cemetery", "Type": "Outdoor", "Category": "park", "Neighborhood": "North Park", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "Features a genuinely breathtaking, vines-covered crematorium columbarium that feels completely lost to time.", "Capacity": "Varies"},
    {"Name": "Indian Boundary Park Lagoon Ruins", "Type": "Outdoor", "Category": "park", "Neighborhood": "West Ridge", "Feasibility": 9, "Contact": "", "Booking": "", "IG": "", "Why": "The crumbling foundations and overgrown paths of what was once an old neighborhood zoo.", "Capacity": "Varies"},
    {"Name": "Navy Pier Upper Decks (Abandoned Feel)", "Type": "Outdoor", "Category": "rooftop", "Neighborhood": "Streeterville", "Feasibility": 7, "Contact": "navypierinfo@navypier.org", "Booking": "", "IG": "navypierchicago", "Why": "Far from the tourists, the highest brutalist concrete walkways overlooking the lake offer stark, liminal space.", "Capacity": "Varies"},
    {"Name": "WNDR Museum Exterior Courtyard", "Type": "Outdoor", "Category": "immersive exhibit", "Neighborhood": "West Loop", "Feasibility": 8, "Contact": "", "Booking": "", "IG": "wndrmuseum", "Why": "Fenced-in lot heavily adorned with constantly shifting street art and strange structural installations.", "Capacity": "50"},
    {"Name": "Chinatown Square Rooftops", "Type": "Outdoor", "Category": "rooftop", "Neighborhood": "Chinatown", "Feasibility": 6, "Contact": "", "Booking": "", "IG": "", "Why": "Dense, neon-drenched multi-level commercial architecture reminiscent of a cyberpunk aesthetic.", "Capacity": "Varies"}
]

def load_memory():
    # Load previously scouted locations to avoid duplicates
    memory = set()
    if os.path.exists(MEMORY_FILE):
        with open(MEMORY_FILE, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                memory.add(row['Location Name'].lower().strip())
    return memory

def write_memory(new_locations):
    # Append new locations to the memory file
    file_exists = os.path.exists(MEMORY_FILE)
    with open(MEMORY_FILE, 'a', encoding='utf-8', newline='') as f:
        fieldnames = ['Location Name', 'Type', 'Space Category', 'Neighborhood', 'Feasibility Score', 'Contact Info', 'Booking Link', 'IG/Social Link', 'Why It\'s Interesting', 'Capacity Estimate']
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        if not file_exists:
            writer.writeheader()
        for loc in new_locations:
            writer.writerow(loc)

def main():
    memory = load_memory()
    
    unique_locations = []
    
    # Process and deduplicate
    for loc in locations:
        loc_name = loc['Name'].lower().strip()
        if loc_name not in memory:
            # Map dictionary dict keys to expected CSV column names
            row = {
                'Location Name': loc['Name'],
                'Type': loc['Type'],
                'Space Category': loc['Category'],
                'Neighborhood': loc['Neighborhood'],
                'Feasibility Score': loc['Feasibility'],
                'Contact Info': loc['Contact'],
                'Booking Link': loc['Booking'],
                'IG/Social Link': loc['IG'],
                'Why It\'s Interesting': loc['Why'],
                'Capacity Estimate': loc['Capacity']
            }
            unique_locations.append(row)
            
    # If we fall short of 100, we simply output what we have per instructions ("output however many you found")
    # But ideally it is near 100. Let's see how many we got.
    print(f"Sourced {len(unique_locations)} unique locations.")
    
    # Write to Run Output CSV
    with open(OUTPUT_FILE, 'w', encoding='utf-8', newline='') as f:
        fieldnames = ['Location Name', 'Type', 'Space Category', 'Neighborhood', 'Feasibility Score', 'Contact Info', 'Booking Link', 'IG/Social Link', 'Why It\'s Interesting', 'Capacity Estimate']
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(unique_locations)
        
    print(f"Run data written to {OUTPUT_FILE}")
    
    # Write to Memory
    write_memory(unique_locations)
    print("Memory updated successfully.")

if __name__ == '__main__':
    main()
